"""Report generators — per-domain modules plus shared context/snapshot components."""

from ...analytics.process_health import generate_process_health
from ...analytics.value_stream import generate_value_stream_map
from ..business_plan import generate_business_plan
from .common import (  # noqa: F401 (re-exported for report_generator facade)
    _looks_like_uuid,
    _serialize_rows,
    _serialize_value,
    attach_public_interest_context,
    build_negative_findings,
    fetch_public_interest_context,
    get_pg,
)
from .commons import (
    generate_adaptive_stewardship,
    generate_adoption_barriers,
    generate_algorithmic_redistribution,
    generate_anti_capture_governance,
    generate_bio_factory_batch,
    generate_bio_input_provenance,
    generate_bio_quality_test,
    generate_bio_recipe_library,
    generate_bio_regional_input,
    generate_capital_alignment,
    generate_community_governance,
    generate_cultural_preservation,
    generate_ecological_modeling,
    generate_federation_mutual_aid,
    generate_foundational_wellbeing,
    generate_gnh_alignment,
    generate_governance_inclusion,
    generate_land_stewardship,
    generate_open_source_impact,
    generate_participatory_signal,
    generate_perpetual_value_stress,
    generate_redistribution_policy,
    generate_regenerative_outcomes,
    generate_renewable_energy,
    generate_replication_readiness,
    generate_scaling_economics,
    generate_time_liberation,
    generate_trophic_pyramid,
    generate_vulnerable_access,
)
from .context import (  # noqa: F401 (re-exported for report_generator facade)
    _check_report_empty,
    _verify_snapshot,
    compute_hash,
    list_snapshots,
    store_snapshot,
)
from .core import (
    generate_climate_impact,
    generate_crop_noi,
    generate_environmental,
    generate_farm_summary,
    generate_forecast_summary,
    generate_revenue_multiplier,
)
from .operations import (
    generate_livestock_feed,
    generate_model_validation,
    generate_organic_certification_readiness,
    generate_organic_input_audit,
    generate_organic_transition_progress,
    generate_pest_management,
    generate_resource_efficiency,
    generate_revenue_streams,
    generate_reward_calibration,
    generate_statement_of_work,
    generate_token_rewards,
    generate_training_impact,
)
from .state import (
    generate_capital_provider_utility,
    generate_comprehensive_status,
    generate_state_of_kokonut,
    generate_state_of_kokonut_graphs,
    generate_strategic_reserve,
)
from .strategy import (
    generate_business_model_canvas,
    generate_capability_assessment,
    generate_capability_dashboard,
    generate_capital_accounting,
    generate_coordination_cockpit,
    generate_data_stream_summary,
    generate_env_scan_report,
    generate_fork_opportunities,
    generate_governance_coordination_health,
    generate_pestel_assessment,
    generate_pin_dependency,
    generate_pitch_deck,
    generate_promotion_ladder,
    generate_publics_market_landscape,
    generate_regional_readiness,
    generate_simulation_wargame,
    generate_stakeholder_cockpit,
    generate_stakeholder_decision_lineage,
    generate_stakeholder_ecosystem,
    generate_stakeholder_engagement,
    generate_stakeholder_grievance,
    generate_stakeholder_landscape,
    generate_stakeholder_outcomes,
    generate_stakeholder_representation,
    generate_stakeholder_trust,
    generate_stakeholder_value_streams,
    generate_strategy_execution,
    generate_tactical_layer,
    generate_technology_roadmap,
    generate_value_stream_formal,
)
from .wellbeing import (
    generate_capital_efficiency,
    generate_dao_proposal_history,
    generate_ebf_scorecard,
    generate_financial_sustainability,
    generate_governance_throughput,
    generate_green_paper_publication_status,
    generate_holistic_wellbeing,
    generate_risk_mitigation,
    generate_scaling_roadmap,
)

REPORT_GENERATORS = {
    "farm_summary": generate_farm_summary,
    "crop_noi": generate_crop_noi,
    "environmental": generate_environmental,
    "revenue_multiplier": generate_revenue_multiplier,
    "forecast": generate_forecast_summary,
    "climate_impact": generate_climate_impact,
    "ebf_scorecard": generate_ebf_scorecard,
    "holistic_wellbeing": generate_holistic_wellbeing,
    "financial_sustainability": generate_financial_sustainability,
    "risk_mitigation": generate_risk_mitigation,
    "scaling_roadmap": generate_scaling_roadmap,
    "green_paper_publication_status": generate_green_paper_publication_status,
    "capital_efficiency": generate_capital_efficiency,
    "governance_throughput": generate_governance_throughput,
    "dao_proposal_history": generate_dao_proposal_history,
    "capital_provider_utility": generate_capital_provider_utility,
    "time_liberation": generate_time_liberation,
    "capital_alignment": generate_capital_alignment,
    "governance_inclusion": generate_governance_inclusion,
    "land_stewardship": generate_land_stewardship,
    "gnh_alignment": generate_gnh_alignment,
    "cultural_preservation": generate_cultural_preservation,
    "renewable_energy": generate_renewable_energy,
    "vulnerable_access": generate_vulnerable_access,
    "foundational_wellbeing": generate_foundational_wellbeing,
    "regenerative_outcomes": generate_regenerative_outcomes,
    "community_governance": generate_community_governance,
    "replication_readiness": generate_replication_readiness,
    "adaptive_stewardship": generate_adaptive_stewardship,
    "scaling_economics": generate_scaling_economics,
    "adoption_barriers": generate_adoption_barriers,
    "perpetual_value_stress": generate_perpetual_value_stress,
    "open_source_impact": generate_open_source_impact,
    "anti_capture_governance": generate_anti_capture_governance,
    "redistribution_policy": generate_redistribution_policy,
    "federation_mutual_aid": generate_federation_mutual_aid,
    "algorithmic_redistribution": generate_algorithmic_redistribution,
    "participatory_signal": generate_participatory_signal,
    "bio_factory_batch": generate_bio_factory_batch,
    "bio_input_provenance": generate_bio_input_provenance,
    "bio_recipe_library": generate_bio_recipe_library,
    "bio_quality_test": generate_bio_quality_test,
    "bio_regional_input": generate_bio_regional_input,
    "ecological_modeling": generate_ecological_modeling,
    "trophic_pyramid": generate_trophic_pyramid,
    "pest_management": generate_pest_management,
    "resource_efficiency": generate_resource_efficiency,
    "training_impact": generate_training_impact,
    "revenue_streams": generate_revenue_streams,
    "model_validation": generate_model_validation,
    "livestock_feed": generate_livestock_feed,
    "token_rewards": generate_token_rewards,
    "reward_calibration": generate_reward_calibration,
    "organic_certification_readiness": generate_organic_certification_readiness,
    "organic_transition_progress": generate_organic_transition_progress,
    "organic_input_audit": generate_organic_input_audit,
    "statement_of_work": generate_statement_of_work,
    "data_stream_summary": generate_data_stream_summary,
    "value_stream_map": generate_value_stream_map,
    "business_plan": generate_business_plan,
    "process_health": generate_process_health,
    "business_model_canvas": generate_business_model_canvas,
    "pitch_deck": generate_pitch_deck,
    "capability_dashboard": generate_capability_dashboard,
    "strategy_execution": generate_strategy_execution,
    "capability_assessment": generate_capability_assessment,
    "value_stream_formal": generate_value_stream_formal,
    "technology_roadmap": generate_technology_roadmap,
    "stakeholder_landscape": generate_stakeholder_landscape,
    "stakeholder_engagement": generate_stakeholder_engagement,
    "stakeholder_grievance": generate_stakeholder_grievance,
    "stakeholder_representation": generate_stakeholder_representation,
    "stakeholder_decision_lineage": generate_stakeholder_decision_lineage,
    "stakeholder_ecosystem": generate_stakeholder_ecosystem,
    "stakeholder_outcomes": generate_stakeholder_outcomes,
    "stakeholder_trust": generate_stakeholder_trust,
    "stakeholder_value_streams": generate_stakeholder_value_streams,
    "stakeholder_cockpit": generate_stakeholder_cockpit,
    "coordination_cockpit": generate_coordination_cockpit,
    "governance_coordination_health": generate_governance_coordination_health,
    "pestel_assessment": generate_pestel_assessment,
    "regional_readiness": generate_regional_readiness,
    "publics_market_landscape": generate_publics_market_landscape,
    "env_scan_report": generate_env_scan_report,
    "state_of_kokonut": generate_state_of_kokonut,
    "state_of_kokonut_graphs": generate_state_of_kokonut_graphs,
    "comprehensive_status": generate_comprehensive_status,
    "strategic_reserve": generate_strategic_reserve,
    "fork_opportunities": generate_fork_opportunities,
    "pin_dependency": generate_pin_dependency,
    "promotion_ladder": generate_promotion_ladder,
    "tactical_layer": generate_tactical_layer,
    "simulation_wargame": generate_simulation_wargame,
    "capital_accounting": generate_capital_accounting,
}

__all__ = [
    "REPORT_GENERATORS",
    "compute_hash",
    "store_snapshot",
    "list_snapshots",
    "build_negative_findings",
    "fetch_public_interest_context",
    "attach_public_interest_context",
    "get_pg",
    "generate_process_health",
    "generate_value_stream_map",
    "generate_business_plan",
    "generate_farm_summary",
    "generate_crop_noi",
    "generate_environmental",
    "generate_revenue_multiplier",
    "generate_forecast_summary",
    "generate_climate_impact",
    "generate_ebf_scorecard",
    "generate_holistic_wellbeing",
    "generate_financial_sustainability",
    "generate_risk_mitigation",
    "generate_scaling_roadmap",
    "generate_green_paper_publication_status",
    "generate_capital_efficiency",
    "generate_governance_throughput",
    "generate_dao_proposal_history",
    "generate_capital_provider_utility",
    "generate_time_liberation",
    "generate_capital_alignment",
    "generate_governance_inclusion",
    "generate_land_stewardship",
    "generate_gnh_alignment",
    "generate_cultural_preservation",
    "generate_renewable_energy",
    "generate_vulnerable_access",
    "generate_foundational_wellbeing",
    "generate_regenerative_outcomes",
    "generate_community_governance",
    "generate_replication_readiness",
    "generate_adaptive_stewardship",
    "generate_scaling_economics",
    "generate_adoption_barriers",
    "generate_perpetual_value_stress",
    "generate_open_source_impact",
    "generate_anti_capture_governance",
    "generate_redistribution_policy",
    "generate_federation_mutual_aid",
    "generate_algorithmic_redistribution",
    "generate_participatory_signal",
    "generate_bio_factory_batch",
    "generate_bio_input_provenance",
    "generate_bio_recipe_library",
    "generate_bio_quality_test",
    "generate_bio_regional_input",
    "generate_ecological_modeling",
    "generate_trophic_pyramid",
    "generate_pest_management",
    "generate_resource_efficiency",
    "generate_training_impact",
    "generate_revenue_streams",
    "generate_model_validation",
    "generate_livestock_feed",
    "generate_token_rewards",
    "generate_reward_calibration",
    "generate_organic_certification_readiness",
    "generate_organic_transition_progress",
    "generate_organic_input_audit",
    "generate_statement_of_work",
    "generate_data_stream_summary",
    "generate_business_model_canvas",
    "generate_pitch_deck",
    "generate_capability_dashboard",
    "generate_strategy_execution",
    "generate_capability_assessment",
    "generate_value_stream_formal",
    "generate_technology_roadmap",
    "generate_stakeholder_landscape",
    "generate_stakeholder_engagement",
    "generate_stakeholder_grievance",
    "generate_stakeholder_representation",
    "generate_stakeholder_decision_lineage",
    "generate_stakeholder_ecosystem",
    "generate_stakeholder_outcomes",
    "generate_stakeholder_trust",
    "generate_stakeholder_value_streams",
    "generate_stakeholder_cockpit",
    "generate_coordination_cockpit",
    "generate_governance_coordination_health",
    "generate_pestel_assessment",
    "generate_regional_readiness",
    "generate_publics_market_landscape",
    "generate_env_scan_report",
    "generate_state_of_kokonut",
    "generate_state_of_kokonut_graphs",
    "generate_comprehensive_status",
    "generate_strategic_reserve",
    "generate_fork_opportunities",
    "generate_pin_dependency",
    "generate_promotion_ladder",
    "generate_tactical_layer",
    "generate_simulation_wargame",
    "generate_capital_accounting",
]

