"""AI summary lifecycle workflow specification."""

from .model import Step, Transition, WorkflowSpec
from .registry import register


AI_SUMMARY = register(WorkflowSpec(
    id="ai_summary",
    title="AI Summary Lifecycle",
    states=frozenset({"draft", "submitted", "verified", "published", "rejected"}),
    invariants=(
        "An AI summary begins in draft, generated by an agent from approved governed data.",
        "Agent-generated summaries must be drafts; agents cannot publish.",
        "Verification requires a human reviewer.",
        "Publication makes the summary available for downstream consumers.",
        "Rejection is terminal and requires a reason.",
    ),
    source_refs=(
        "schemas/postgres/007_modeled_outputs.sql",
        "services/agents/ai_summary.py",
    ),
    steps=(
        Step("ais_draft_entry", "generator", "draft", "Generate AI summary", entry=True, transitions=(
            Transition("ais_submit", "submitted", "submit for review", "submit"),
            Transition("ais_reject_draft", "rejected", "withdrawn before submission", "reject"),
        )),
        Step("ais_submit", "generator", "submitted", "Submit summary for review", transitions=(
            Transition("ais_verify", "verified", "reviewed and verified", "verify"),
            Transition("ais_reject_submitted", "rejected", "rejected during review", "reject"),
        )),
        Step("ais_verify", "reviewer", "verified", "Verify summary accuracy", human_approval=True, transitions=(
            Transition("ais_publish", "published", "approved for publication", "publish"),
            Transition("ais_reject_verified", "rejected", "rejected after verification", "reject"),
        )),
        Step("ais_publish", "system", "published", "Terminal published summary", terminal=True),
        Step("ais_reject_draft", "reviewer", "rejected", "Terminal rejected summary", terminal=True),
        Step("ais_reject_submitted", "reviewer", "rejected", "Terminal rejected summary", terminal=True),
        Step("ais_reject_verified", "reviewer", "rejected", "Terminal rejected summary", terminal=True),
    ),
))
