"""Report snapshot lifecycle workflow specification."""

from .model import Step, Transition, WorkflowSpec
from .registry import register

REPORT_SNAPSHOT = register(WorkflowSpec(
    id="report_snapshot",
    title="Report Snapshot Lifecycle",
    states=frozenset({"draft", "submitted", "verified", "published", "rejected"}),
    invariants=(
        "A report snapshot begins in draft, generated by the report generator.",
        "Report snapshots include public-interest context and uncertainty notes.",
        "Verification ensures data accuracy and completeness.",
        "Publication makes the report available for downstream consumers.",
        "Rejection is terminal and requires a reason.",
    ),
    source_refs=(
        "schemas/postgres/007_modeled_outputs.sql",
        "services/export/report_generator.py",
    ),
    steps=(
        Step("rs_draft_entry", "generator", "draft", "Generate report snapshot", entry=True, transitions=(
            Transition("rs_submit", "submitted", "submit for review", "submit"),
            Transition("rs_reject_draft", "rejected", "withdrawn before review", "reject"),
        )),
        Step("rs_submit", "generator", "submitted", "Submit report for review", transitions=(
            Transition("rs_verify", "verified", "reviewed and verified", "verify"),
            Transition("rs_reject_submitted", "rejected", "rejected during review", "reject"),
        )),
        Step("rs_verify", "reviewer", "verified", "Verify report accuracy", human_approval=True, transitions=(
            Transition("rs_publish", "published", "approved for publication", "publish"),
            Transition("rs_reject_verified", "rejected", "rejected after verification", "reject"),
        )),
        Step("rs_publish", "system", "published", "Terminal published report", terminal=True),
        Step("rs_reject_draft", "reviewer", "rejected", "Terminal rejected report", terminal=True),
        Step("rs_reject_submitted", "reviewer", "rejected", "Terminal rejected report", terminal=True),
        Step("rs_reject_verified", "reviewer", "rejected", "Terminal rejected report", terminal=True),
    ),
))
