-- ============================================================
-- 030_pilot_financial_resilience.sql — Adelphi sustainability, risk, scaling, and publication review examples
-- ============================================================

INSERT INTO financial_sustainability_plan (
    id, location_id, farm_id, plan_name, farm_model, plan_period_start, plan_period_end,
    revenue_streams, grant_dependency_pct, reinvestment_pct, public_goods_allocation_pct,
    break_even_month, runway_months, projected_annual_revenue_usd,
    projected_annual_operating_cost_usd, projected_annual_noi_usd, sustainability_status,
    strategy_summary, public_summary, evidence_maturity, status, metadata,
    source_system, source_id, source_raw
) VALUES (
    'a0000000-0000-0000-0000-000000001000',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    'Adelphi 2026 transition to reinvested operations',
    'blended',
    '2026-04-01',
    '2027-03-31',
    ARRAY['lettuce', 'passion_fruit', 'coconut', 'eggs', 'indian_yam', 'nursery', 'bioinputs', 'impact_verification_sponsorship'],
    35.0000,
    20.0000,
    10.0000,
    14,
    9.5000,
    24500.00,
    15300.00,
    9200.00,
    'transitioning',
    'Adelphi uses a blended model: early DAO and public-goods funding de-risks establishment while crop sales, nursery outputs, bioinputs, and impact-verification sponsorships increase the share of self-funded operations.',
    'Adelphi is transitioning from grant-supported establishment toward reinvested operations, with 10% public-goods allocation and 20% reinvestment target documented for 2026.',
    3,
    'published',
    '{"source_forecast_id":"a0000000-0000-0000-0000-000000000081","source_cash_flow_snapshots":["a0000000-0000-0000-0000-000000000340","a0000000-0000-0000-0000-000000000341"],"grant_dependency_target_pct_2027":20}'::jsonb,
    'pilot_seed',
    'adelphi-financial-sustainability-2026',
    '{"record_type":"financial_sustainability_plan","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    plan_name = EXCLUDED.plan_name,
    farm_model = EXCLUDED.farm_model,
    revenue_streams = EXCLUDED.revenue_streams,
    grant_dependency_pct = EXCLUDED.grant_dependency_pct,
    reinvestment_pct = EXCLUDED.reinvestment_pct,
    public_goods_allocation_pct = EXCLUDED.public_goods_allocation_pct,
    break_even_month = EXCLUDED.break_even_month,
    runway_months = EXCLUDED.runway_months,
    projected_annual_revenue_usd = EXCLUDED.projected_annual_revenue_usd,
    projected_annual_operating_cost_usd = EXCLUDED.projected_annual_operating_cost_usd,
    projected_annual_noi_usd = EXCLUDED.projected_annual_noi_usd,
    sustainability_status = EXCLUDED.sustainability_status,
    strategy_summary = EXCLUDED.strategy_summary,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();

INSERT INTO risk_mitigation_register (
    id, location_id, farm_id, risk_category, risk_description, likelihood, impact_level,
    mitigation_strategy, insurance_scope, oversight_mechanism, technical_support_provider,
    owner_role, review_cadence, residual_risk_level, review_date, next_review_date,
    public_summary, evidence_maturity, status, metadata, source_system, source_id, source_raw
) VALUES
(
    'a0000000-0000-0000-0000-000000001010',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    'climate',
    'Drought or irregular rainfall may reduce yield and stress young agroforestry systems.',
    'medium',
    'high',
    'Maintain water storage, irrigation monitoring, mulching, living cover, and conservative forecast scenarios with drought assumptions.',
    'Annual crop insurance premium recorded as a governed expense; exact policy coverage remains internal until insurer documentation is publishable.',
    'Quarterly operator review of water and climate indicators through environmental baselines and field notes.',
    'Dominican Agronomy Advisors and Kokonut Impact Guild',
    'Impact Guild',
    'quarterly',
    'medium',
    '2026-03-10',
    '2026-06-30',
    'Climate risk is mitigated through water storage, living soil cover, crop insurance evidence, and conservative forecasting.',
    3,
    'published',
    '{"insurance_expense_id":"e0000000-0000-0000-0000-000000000029","forecast_scenario_id":"a0000000-0000-0000-0000-000000000082"}'::jsonb,
    'pilot_seed',
    'adelphi-risk-climate-2026-03',
    '{"record_type":"risk_mitigation_register"}'::jsonb
),
(
    'a0000000-0000-0000-0000-000000001011',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    'market',
    'Revenue projections depend on buyer access, crop mix, and price stability for local produce and nursery outputs.',
    'medium',
    'medium',
    'Diversify revenue streams across crops, nursery outputs, bioinputs, direct buyers, and impact verification sponsorships.',
    NULL,
    'Finance Guild reviews sales, cash flow, and value-flow records each reporting cycle.',
    'Finance Guild and Community & Partnerships Guild',
    'Finance Guild',
    'quarterly',
    'medium',
    '2026-03-10',
    '2026-06-30',
    'Market risk is mitigated by diversified revenue streams and quarterly finance review of sales and cash-flow evidence.',
    3,
    'published',
    '{"revenue_stream_count":8,"source_plan_id":"a0000000-0000-0000-0000-000000001000"}'::jsonb,
    'pilot_seed',
    'adelphi-risk-market-2026-03',
    '{"record_type":"risk_mitigation_register"}'::jsonb
),
(
    'a0000000-0000-0000-0000-000000001012',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    'evidence_quality',
    'Public claims can lose credibility if source lineage, CIDs, hashes, maturity labels, or reviewer notes are incomplete.',
    'medium',
    'high',
    'Use evidence maturity gates, public-safe views, CIDS export, and Green Paper publication review before public claims.',
    NULL,
    'Reviewer Guide and Evidence Gap dashboard before publication.',
    'Impact Guild and Communications Guild',
    'Impact Guild',
    'monthly',
    'low',
    '2026-03-10',
    '2026-04-30',
    'Evidence-quality risk is mitigated through maturity gates, public-safe views, CIDS export, and publication review.',
    3,
    'published',
    '{"green_paper_review_id":"a0000000-0000-0000-0000-000000001030"}'::jsonb,
    'pilot_seed',
    'adelphi-risk-evidence-quality-2026-03',
    '{"record_type":"risk_mitigation_register"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    risk_category = EXCLUDED.risk_category,
    risk_description = EXCLUDED.risk_description,
    likelihood = EXCLUDED.likelihood,
    impact_level = EXCLUDED.impact_level,
    mitigation_strategy = EXCLUDED.mitigation_strategy,
    insurance_scope = EXCLUDED.insurance_scope,
    oversight_mechanism = EXCLUDED.oversight_mechanism,
    technical_support_provider = EXCLUDED.technical_support_provider,
    owner_role = EXCLUDED.owner_role,
    review_cadence = EXCLUDED.review_cadence,
    residual_risk_level = EXCLUDED.residual_risk_level,
    review_date = EXCLUDED.review_date,
    next_review_date = EXCLUDED.next_review_date,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();

INSERT INTO scaling_roadmap_milestone (
    id, roadmap_name, location_id, target_region, farm_model, planned_farm_count,
    capital_required_usd, partner_requirements, operational_dependencies, risk_gates,
    target_date, milestone_status, public_summary, evidence_maturity, status, metadata
) VALUES
(
    'a0000000-0000-0000-0000-000000001020',
    'Adelphi replication readiness',
    'a0000000-0000-0000-0000-000000000001',
    'Dominican Republic pilot cluster',
    'blended',
    2,
    35000.00,
    ARRAY['local buyer agreements', 'agronomy advisor coverage', 'community operator onboarding', 'impact verification partner'],
    ARRAY['published financial sustainability plan', 'risk mitigation register', 'Spanish operator summaries', 'verified EBF scorecard'],
    ARRAY['runway >= 6 months', 'risk mitigation coverage >= 80%', 'public claims maturity gates satisfied'],
    '2026-12-31',
    'planned',
    'Adelphi replication readiness targets two additional Dominican pilot farms after financial, risk, operator, and evidence gates are met.',
    3,
    'published',
    '{"source_plan_id":"a0000000-0000-0000-0000-000000001000","scaling_caveat":"roadmap milestone, not guaranteed expansion"}'::jsonb
),
(
    'a0000000-0000-0000-0000-000000001021',
    'Public-goods farm playbook',
    NULL,
    'Celo/Gnosis aligned ReFi partner network',
    'public_good_optimized',
    4,
    80000.00,
    ARRAY['public goods funders', 'local cooperative partner', 'open-source operator playbook', 'CIDS-compatible reporting'],
    ARRAY['Green Paper V1 publication', 'financial sustainability dashboard', 'participatory governance dashboard'],
    ARRAY['publication review completed', 'grant dependency reduction plan', 'community feedback loop active'],
    '2027-06-30',
    'planned',
    'The public-goods farm playbook milestone turns Kokonut implementation evidence into a repeatable, governed expansion path.',
    3,
    'published',
    '{"green_paper_dependency":"v1 publication","scaling_caveat":"resource projection for review"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    roadmap_name = EXCLUDED.roadmap_name,
    target_region = EXCLUDED.target_region,
    farm_model = EXCLUDED.farm_model,
    planned_farm_count = EXCLUDED.planned_farm_count,
    capital_required_usd = EXCLUDED.capital_required_usd,
    partner_requirements = EXCLUDED.partner_requirements,
    operational_dependencies = EXCLUDED.operational_dependencies,
    risk_gates = EXCLUDED.risk_gates,
    target_date = EXCLUDED.target_date,
    milestone_status = EXCLUDED.milestone_status,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();

INSERT INTO green_paper_publication_review (
    id, version, document_path, review_status, review_owner, review_started_at,
    target_publication_date, open_questions, approval_records, public_summary,
    evidence_maturity, status, metadata
) VALUES (
    'a0000000-0000-0000-0000-000000001030',
    '1.0',
    'docs/green-paper-v1.md',
    'stakeholder_review',
    'Communications Guild',
    '2026-06-01 00:00:00+00',
    '2026-07-31',
    '[{"topic":"stakeholder approval","status":"pending"},{"topic":"publication artifact CID","status":"pending"}]'::jsonb,
    '[{"reviewer":"Impact Guild","status":"approved_for_review","date":"2026-06-27"}]'::jsonb,
    'Green Paper V1 is in stakeholder review with publication proof metadata pending before final public release.',
    3,
    'verified',
    '{"publication_boundary":"draft_until_stakeholder_approval_and_artifact_hash"}'::jsonb
)
ON CONFLICT (version, document_path) DO UPDATE SET
    review_status = EXCLUDED.review_status,
    review_owner = EXCLUDED.review_owner,
    review_started_at = EXCLUDED.review_started_at,
    target_publication_date = EXCLUDED.target_publication_date,
    open_questions = EXCLUDED.open_questions,
    approval_records = EXCLUDED.approval_records,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();
