-- ============================================================
-- 031_pilot_capital_efficiency.sql — Adelphi capital efficiency, ROI scenario, and governance throughput examples
-- ============================================================

INSERT INTO capital_efficiency_scenario (
    id, location_id, farm_id, scenario_name, scenario_type, period_start, period_end,
    capital_deployed_usd, gross_output_value_usd, net_output_value_usd, public_goods_value_usd,
    capital_leverage_ratio, efficiency_summary, public_summary, evidence_maturity, status,
    metadata, source_system, source_id, source_raw
) VALUES (
    'a0000000-0000-0000-0000-000000001100',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    'Adelphi 2026 blended capital efficiency scenario',
    'public_goods_loop',
    '2026-04-01',
    '2027-03-31',
    24500.00,
    24500.00,
    9200.00,
    2450.00,
    1.1000,
    'The scenario compares projected annual output and public-goods allocation against capital deployed for Adelphi 2026 operations. It uses existing forecast and sustainability-plan evidence and avoids claiming guaranteed returns.',
    'Adelphi projects roughly $24.5k in annual output and $2.45k public-goods allocation against $24.5k deployed capital, producing a 1.10x gross-plus-public-goods leverage signal before risk gates.',
    3,
    'published',
    '{"source_plan_id":"a0000000-0000-0000-0000-000000001000","forecast_id":"a0000000-0000-0000-0000-000000000081","scenario_limit":"planning_signal_not_return_guarantee"}'::jsonb,
    'pilot_seed',
    'adelphi-capital-efficiency-2026',
    '{"record_type":"capital_efficiency_scenario","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    scenario_name = EXCLUDED.scenario_name,
    scenario_type = EXCLUDED.scenario_type,
    capital_deployed_usd = EXCLUDED.capital_deployed_usd,
    gross_output_value_usd = EXCLUDED.gross_output_value_usd,
    net_output_value_usd = EXCLUDED.net_output_value_usd,
    public_goods_value_usd = EXCLUDED.public_goods_value_usd,
    capital_leverage_ratio = EXCLUDED.capital_leverage_ratio,
    efficiency_summary = EXCLUDED.efficiency_summary,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();

INSERT INTO regenerative_efficiency_observation (
    id, location_id, farm_id, practice_event_id, observation_date, practice_type,
    baseline_cost_usd, observed_cost_usd, cost_savings_pct, incremental_output_value_usd,
    implementation_cost_usd, payback_months, efficiency_summary, public_summary,
    evidence_maturity, status, metadata, source_system, source_id, source_raw
) VALUES (
    'a0000000-0000-0000-0000-000000001110',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    (SELECT id FROM farm_practice_event WHERE source_id = 'adelphi-practice-bioinputs-2025-10' LIMIT 1),
    '2026-03-31',
    'bioinput_production',
    1200.00,
    420.00,
    65.0000,
    850.00,
    1800.00,
    13.2000,
    'Bioinput production compares a conservative conventional input baseline with observed biofactory operating cost and expected incremental nursery/crop value. Payback is scenario-based and should be recalculated as actual harvest and expense records mature.',
    'Adelphi bioinput production shows a conservative 65% input-cost savings scenario with estimated 13.2-month payback, subject to continued validation through expense and harvest records.',
    3,
    'published',
    '{"input_category":"bioinputs","scenario_limit":"observed_cost_plus_forecasted_output"}'::jsonb,
    'pilot_seed',
    'adelphi-bioinput-efficiency-2026-03',
    '{"record_type":"regenerative_efficiency_observation","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    practice_event_id = EXCLUDED.practice_event_id,
    observation_date = EXCLUDED.observation_date,
    practice_type = EXCLUDED.practice_type,
    baseline_cost_usd = EXCLUDED.baseline_cost_usd,
    observed_cost_usd = EXCLUDED.observed_cost_usd,
    cost_savings_pct = EXCLUDED.cost_savings_pct,
    incremental_output_value_usd = EXCLUDED.incremental_output_value_usd,
    implementation_cost_usd = EXCLUDED.implementation_cost_usd,
    payback_months = EXCLUDED.payback_months,
    efficiency_summary = EXCLUDED.efficiency_summary,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();

INSERT INTO governance_throughput_observation (
    id, location_id, dao_proposal_id, proposal_code, venue, proposal_type,
    proposal_created_at, decision_at, executed_at, decision_latency_days, execution_latency_days,
    decision_result, governance_summary, public_summary, evidence_maturity, status,
    metadata, source_system, source_id, source_raw
) VALUES
(
    'a0000000-0000-0000-0000-000000001120',
    'a0000000-0000-0000-0000-000000000001',
    (SELECT id FROM dao_proposal WHERE proposal_code = 'KOK-AD-001'),
    'P001',
    'daohaus',
    'farm_funding',
    '2025-10-15 09:00:00+00',
    '2025-10-20 14:00:00+00',
    '2025-10-20 14:00:00+00',
    5.2100,
    5.2100,
    'executed',
    'Adelphi farm funding moved from proposal creation to execution in just over five days based on seeded Gnosis/Moloch governance events.',
    'Adelphi farm funding proposal P001 executed about 5.2 days after creation, providing an initial governance-throughput benchmark for DAO-funded farm operations.',
    3,
    'published',
    '{"source_events":["proposal_created","vote_cast","proposal_executed"],"governance_layer":"moloch_v2"}'::jsonb,
    'pilot_seed',
    'adelphi-governance-throughput-p001',
    '{"record_type":"governance_throughput_observation","privacy":"public_summary"}'::jsonb
),
(
    'a0000000-0000-0000-0000-000000001121',
    'a0000000-0000-0000-0000-000000000001',
    NULL,
    'P002',
    'daohaus',
    'farm_funding',
    '2025-11-01 09:00:00+00',
    '2025-11-06 14:00:00+00',
    '2025-11-06 14:00:00+00',
    5.2100,
    5.2100,
    'executed',
    'Biofactory and nursery maintenance funding moved from proposal creation to execution in just over five days based on seeded Gnosis/Moloch governance events.',
    'Biofactory and nursery funding proposal P002 executed about 5.2 days after creation, showing comparable throughput for operating-capital decisions.',
    3,
    'published',
    '{"source_events":["proposal_created","vote_cast","proposal_executed"],"governance_layer":"moloch_v2"}'::jsonb,
    'pilot_seed',
    'adelphi-governance-throughput-p002',
    '{"record_type":"governance_throughput_observation","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (proposal_code, source_system, source_id) DO UPDATE SET
    location_id = EXCLUDED.location_id,
    dao_proposal_id = EXCLUDED.dao_proposal_id,
    venue = EXCLUDED.venue,
    proposal_type = EXCLUDED.proposal_type,
    proposal_created_at = EXCLUDED.proposal_created_at,
    decision_at = EXCLUDED.decision_at,
    executed_at = EXCLUDED.executed_at,
    decision_latency_days = EXCLUDED.decision_latency_days,
    execution_latency_days = EXCLUDED.execution_latency_days,
    decision_result = EXCLUDED.decision_result,
    governance_summary = EXCLUDED.governance_summary,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();

INSERT INTO capital_provider_utility_scenario (
    id, location_id, farm_id, capital_source_id, scenario_name, provider_type,
    capital_amount_usd, expected_financial_return_usd, expected_public_goods_value_usd,
    expected_verification_outputs, expected_payback_months, utility_score,
    utility_summary, public_summary, limitations, evidence_maturity, status,
    metadata, source_system, source_id, source_raw
) VALUES (
    'a0000000-0000-0000-0000-000000001130',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    NULL,
    'Adelphi sponsor-supported verification utility scenario',
    'sponsor',
    5000.00,
    0.00,
    2450.00,
    6,
    NULL,
    7.2500,
    'This scenario frames sponsor utility as public-goods allocation, verified reports, CIDS-compatible outputs, and learning value rather than promised financial return.',
    'A $5k sponsor-supported scenario for Adelphi would prioritize public-goods allocation, six verification/reporting outputs, and reusable learning value; it does not promise financial return.',
    ARRAY['Scenario evidence only; not an offer of securities or guaranteed return.', 'Public-goods value is estimated from the published financial sustainability plan.', 'Private sponsorship terms are excluded from public reporting.'],
    3,
    'published',
    '{"source_plan_id":"a0000000-0000-0000-0000-000000001000","utility_components":["public_goods","verification_outputs","learning_value"]}'::jsonb,
    'pilot_seed',
    'adelphi-sponsor-utility-2026',
    '{"record_type":"capital_provider_utility_scenario","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    scenario_name = EXCLUDED.scenario_name,
    provider_type = EXCLUDED.provider_type,
    capital_amount_usd = EXCLUDED.capital_amount_usd,
    expected_financial_return_usd = EXCLUDED.expected_financial_return_usd,
    expected_public_goods_value_usd = EXCLUDED.expected_public_goods_value_usd,
    expected_verification_outputs = EXCLUDED.expected_verification_outputs,
    expected_payback_months = EXCLUDED.expected_payback_months,
    utility_score = EXCLUDED.utility_score,
    utility_summary = EXCLUDED.utility_summary,
    public_summary = EXCLUDED.public_summary,
    limitations = EXCLUDED.limitations,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();
