-- ============================================================
-- 038_pilot_commons_liberation.sql — Adelphi commons liberation and stewardship examples
-- ============================================================

INSERT INTO time_liberation_observation (
    id, location_id, farm_id, observation_date, workflow_area,
    baseline_hours, observed_hours, hours_reclaimed, burden_reduction_pct,
    automation_or_agent_used, automation_type, beneficiary_group,
    liberation_summary, public_summary, evidence_maturity, status,
    metadata, source_system, source_id, source_raw
) VALUES (
    'a0000000-0000-0000-0000-000000001200',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    '2026-03-31',
    'monthly_operator_reporting',
    8.0000,
    5.0000,
    3.0000,
    37.5000,
    TRUE,
    'ai_summary_and_csv_templates',
    'farm_operator',
    'Adelphi uses governed CSV templates, public-safe report snapshots, and draft-only AI summaries to reduce repetitive reporting work while keeping human review and local-language needs visible.',
    'Adelphi estimates three hours of monthly operator reporting time reclaimed through templates and draft AI summaries, with human review still required before publication.',
    3,
    'published',
    '{"source_feedback_id":"a0000000-0000-0000-0000-000000000900","local_language_need":"Spanish summaries remain part of the workflow"}'::jsonb,
    'pilot_seed',
    'adelphi-time-liberation-reporting-2026-03',
    '{"record_type":"time_liberation_observation","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    observation_date = EXCLUDED.observation_date,
    workflow_area = EXCLUDED.workflow_area,
    baseline_hours = EXCLUDED.baseline_hours,
    observed_hours = EXCLUDED.observed_hours,
    hours_reclaimed = EXCLUDED.hours_reclaimed,
    burden_reduction_pct = EXCLUDED.burden_reduction_pct,
    automation_or_agent_used = EXCLUDED.automation_or_agent_used,
    automation_type = EXCLUDED.automation_type,
    beneficiary_group = EXCLUDED.beneficiary_group,
    liberation_summary = EXCLUDED.liberation_summary,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();

INSERT INTO capital_alignment_assessment (
    id, location_id, farm_id, capital_source_id, assessment_date,
    provider_name, provider_type, alignment_status, extractive_risk_level,
    community_control_terms, exit_pressure_risk, profit_extraction_limits,
    commons_reinvestment_commitment_pct, assessment_summary, public_summary,
    evidence_maturity, status, metadata, source_system, source_id, source_raw
) VALUES (
    'a0000000-0000-0000-0000-000000001210',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    NULL,
    '2026-03-31',
    'Kokonut DAO and public-goods funders',
    'public_goods_funder',
    'aligned',
    'low',
    'Governed records prioritize DAO/public-goods funding, public summaries, and farm/operator review rather than unilateral investor control.',
    'No forced exit timing is documented in the public scenario; private funding terms are excluded until publishable.',
    'Published plans emphasize reinvestment and public-goods allocation instead of guaranteed distributions.',
    10.0000,
    'Adelphi capital alignment is assessed as low extractive risk because public records emphasize DAO/public-goods funding context, 10% public-goods allocation, reinvestment, and no guaranteed investor return claim.',
    'Adelphi public capital evidence prioritizes DAO/public-goods funding, 10% commons allocation, and reinvestment while excluding private terms and guaranteed-return claims.',
    3,
    'published',
    '{"source_financial_plan_id":"a0000000-0000-0000-0000-000000001000","source_utility_scenario_id":"a0000000-0000-0000-0000-000000001130"}'::jsonb,
    'pilot_seed',
    'adelphi-capital-alignment-2026-03',
    '{"record_type":"capital_alignment_assessment","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    assessment_date = EXCLUDED.assessment_date,
    provider_name = EXCLUDED.provider_name,
    provider_type = EXCLUDED.provider_type,
    alignment_status = EXCLUDED.alignment_status,
    extractive_risk_level = EXCLUDED.extractive_risk_level,
    community_control_terms = EXCLUDED.community_control_terms,
    exit_pressure_risk = EXCLUDED.exit_pressure_risk,
    profit_extraction_limits = EXCLUDED.profit_extraction_limits,
    commons_reinvestment_commitment_pct = EXCLUDED.commons_reinvestment_commitment_pct,
    assessment_summary = EXCLUDED.assessment_summary,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();

INSERT INTO governance_inclusion_observation (
    id, location_id, dao_proposal_id, observation_date, governance_body,
    inclusion_scope, represented_groups, missing_groups, pseudonymous_participation_enabled,
    marginalized_voice_count, total_participant_count, representation_coverage_pct,
    inclusion_summary, public_summary, evidence_maturity, status,
    metadata, source_system, source_id, source_raw
) VALUES (
    'a0000000-0000-0000-0000-000000001220',
    'a0000000-0000-0000-0000-000000000001',
    (SELECT id FROM dao_proposal WHERE proposal_code = 'KOK-AD-002'),
    '2026-03-31',
    'Adelphi Impact and MRV Guild review',
    'guild',
    ARRAY['farm_operator', 'impact_guild', 'community_partnerships_guild', 'technology_guild'],
    ARRAY['additional local-language reviewer', 'privacy-preserving pseudonymous contributor path'],
    TRUE,
    2,
    4,
    75.0000,
    'Adelphi governance inclusion currently documents farm-operator, impact, community-partnerships, and technology representation. A privacy-preserving pseudonymous contribution path is allowed for public-goods work, but local-language review coverage should improve.',
    'Adelphi governance includes farm-operator, impact, community, and technology voices, with pseudonymous contribution allowed where accountability and safety gates are preserved.',
    3,
    'published',
    '{"source_guild_contributions":["a0000000-0000-0000-0000-000000000810","a0000000-0000-0000-0000-000000000811","a0000000-0000-0000-0000-000000000812"],"unsupported_claims_excluded":["Kokonut Venus Farm"]}'::jsonb,
    'pilot_seed',
    'adelphi-governance-inclusion-2026-03',
    '{"record_type":"governance_inclusion_observation","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    dao_proposal_id = EXCLUDED.dao_proposal_id,
    observation_date = EXCLUDED.observation_date,
    governance_body = EXCLUDED.governance_body,
    inclusion_scope = EXCLUDED.inclusion_scope,
    represented_groups = EXCLUDED.represented_groups,
    missing_groups = EXCLUDED.missing_groups,
    pseudonymous_participation_enabled = EXCLUDED.pseudonymous_participation_enabled,
    marginalized_voice_count = EXCLUDED.marginalized_voice_count,
    total_participant_count = EXCLUDED.total_participant_count,
    representation_coverage_pct = EXCLUDED.representation_coverage_pct,
    inclusion_summary = EXCLUDED.inclusion_summary,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();

INSERT INTO land_stewardship_commitment (
    id, location_id, farm_id, tenure_rights_assessment_id, commitment_date,
    stewardship_model, landlord_dependency_risk, anti_speculation_terms,
    community_benefit_rights, commons_transition_path, land_access_summary,
    public_summary, evidence_maturity, status, metadata, source_system, source_id, source_raw
) VALUES (
    'a0000000-0000-0000-0000-000000001230',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    'a0000000-0000-0000-0000-000000000690',
    '2026-03-31',
    'family_stewardship_with_public_goods',
    'low',
    'Published records emphasize managed-area boundaries, public-goods allocation, and no speculative land-sale claim; legal anti-speculation terms remain outside public evidence until documented.',
    'Community benefit rights are represented through local hiring, bioinput skill transfer, public summaries, and 10% public-goods allocation commitments.',
    'Near-term path is stewardship-with-public-goods evidence; any future commons trust or collective title claim would require separate legal and governed documentation.',
    'Adelphi is documented as communal/community-first tenure context with public-good commitments, but the record does not claim landlord abolition or legal transfer of land ownership.',
    'Adelphi land stewardship is framed as community-first managed-area stewardship with public-goods commitments, not as an unsupported claim of land transfer or landlord abolition.',
    3,
    'published',
    '{"source_tenure_assessment_id":"a0000000-0000-0000-0000-000000000690","claim_boundary":"no legal land transfer claim"}'::jsonb,
    'pilot_seed',
    'adelphi-land-stewardship-2026-03',
    '{"record_type":"land_stewardship_commitment","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    tenure_rights_assessment_id = EXCLUDED.tenure_rights_assessment_id,
    commitment_date = EXCLUDED.commitment_date,
    stewardship_model = EXCLUDED.stewardship_model,
    landlord_dependency_risk = EXCLUDED.landlord_dependency_risk,
    anti_speculation_terms = EXCLUDED.anti_speculation_terms,
    community_benefit_rights = EXCLUDED.community_benefit_rights,
    commons_transition_path = EXCLUDED.commons_transition_path,
    land_access_summary = EXCLUDED.land_access_summary,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();
