-- ============================================================
-- 039_pilot_gnh_alignment.sql — Adelphi GNH alignment, cultural preservation, renewable energy, access, and foundational well-being examples
-- ============================================================

INSERT INTO gnh_alignment_assessment (
    id, location_id, farm_id, assessment_date, gnh_domain, principle_refs,
    alignment_score, strengths, gaps, safeguards, assessment_summary, public_summary,
    evidence_maturity, status, metadata, source_system, source_id, source_raw
) VALUES
(
    'a0000000-0000-0000-0000-000000001300',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    '2026-03-31',
    'ecological_diversity',
    ARRAY['GNH-17', 'GNH-18', 'GNH-19'],
    8.0000,
    ARRAY['syntropic agroforestry evidence', 'bioinput practice records', 'public environmental dashboards'],
    ARRAY['renewable energy planning is not yet implemented evidence'],
    ARRAY['separate planned renewable energy from implemented climate claims'],
    'Adelphi aligns strongly with ecological diversity through syntropic beds, biofactory practice, and environmental evidence, while renewable-energy infrastructure remains a planning gap.',
    'Adelphi has strong public ecological evidence, with renewable energy documented as a planned improvement rather than an implemented claim.',
    3,
    'published',
    '{"scope":"Adelphi only","bhutan_readiness":"requires local review before any Bhutan-specific claim"}'::jsonb,
    'pilot_seed',
    'adelphi-gnh-ecological-diversity-2026-03',
    '{"record_type":"gnh_alignment_assessment","privacy":"public_summary"}'::jsonb
),
(
    'a0000000-0000-0000-0000-000000001301',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    '2026-03-31',
    'culture',
    ARRAY['GNH-9', 'GNH-10', 'GNH-11'],
    6.5000,
    ARRAY['Spanish-language reporting need is documented', 'cultural context records are consent-gated'],
    ARRAY['traditional-practice preservation plan is early-stage', 'no Bhutan-specific cultural review is claimed'],
    ARRAY['local reviewer role required before cultural expansion claims', 'private cultural knowledge stays private'],
    'Adelphi has initial cultural and local-language evidence but should deepen traditional-practice documentation and local-review workflows before making stronger cultural claims.',
    'Adelphi cultural alignment is emerging: Spanish-language reporting and consent-gated cultural summaries exist, while deeper local cultural preservation remains a planned improvement.',
    3,
    'published',
    '{"unsupported_claims_excluded":["Kokonut Venus Farm","Bhutan readiness"]}'::jsonb,
    'pilot_seed',
    'adelphi-gnh-culture-2026-03',
    '{"record_type":"gnh_alignment_assessment","privacy":"public_summary"}'::jsonb
),
(
    'a0000000-0000-0000-0000-000000001302',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    '2026-03-31',
    'community_vitality',
    ARRAY['GNH-5', 'GNH-6', 'GNH-7', 'GNH-8'],
    7.2500,
    ARRAY['participatory action records', 'governance inclusion observation', 'women-led Adelphi metadata'],
    ARRAY['broader vulnerable-group access plan is not yet implemented'],
    ARRAY['use group summaries only and avoid raw protected-class data'],
    'Adelphi community vitality is supported by participatory governance, women-led metadata, and public summaries, but broader access accommodations remain in planning status.',
    'Adelphi has public community-participation evidence and women-led metadata; broader vulnerable-group access is documented as planned, not complete.',
    3,
    'published',
    '{"source_governance_inclusion":"a0000000-0000-0000-0000-000000001220"}'::jsonb,
    'pilot_seed',
    'adelphi-gnh-community-vitality-2026-03',
    '{"record_type":"gnh_alignment_assessment","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    assessment_date = EXCLUDED.assessment_date,
    gnh_domain = EXCLUDED.gnh_domain,
    principle_refs = EXCLUDED.principle_refs,
    alignment_score = EXCLUDED.alignment_score,
    strengths = EXCLUDED.strengths,
    gaps = EXCLUDED.gaps,
    safeguards = EXCLUDED.safeguards,
    assessment_summary = EXCLUDED.assessment_summary,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();

INSERT INTO cultural_preservation_plan (
    id, location_id, farm_id, cultural_context_record_id, plan_date,
    cultural_element, preservation_type, local_language, traditional_practice_summary,
    digital_integration_strategy, consent_protocol, local_reviewer_role,
    implementation_status, public_summary, evidence_maturity, status,
    metadata, source_system, source_id, source_raw
) VALUES (
    'a0000000-0000-0000-0000-000000001310',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    (SELECT id FROM cultural_context_record WHERE source_id = 'adelphi-cultural-syntropic-biofactory-2026-03' LIMIT 1),
    '2026-03-31',
    'Spanish operator summaries and local regenerative practice context',
    'local_language',
    'es',
    'Adelphi operators connect syntropic beds and bioinput work to local agronomic learning; stronger traditional-practice documentation requires local reviewer approval.',
    'Use public summaries, translated operator dashboards, and consented cultural-context records rather than raw private feedback.',
    'Public cultural evidence requires consent, public scope, non-empty public summary, and published lifecycle status.',
    'Community Partnerships Guild',
    'planned',
    'Adelphi plans to deepen Spanish-language and local-practice preservation through consented public summaries and local reviewer participation.',
    3,
    'published',
    '{"claim_boundary":"not a Bhutan cultural-readiness claim"}'::jsonb,
    'pilot_seed',
    'adelphi-cultural-preservation-2026-03',
    '{"record_type":"cultural_preservation_plan","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    cultural_context_record_id = EXCLUDED.cultural_context_record_id,
    plan_date = EXCLUDED.plan_date,
    cultural_element = EXCLUDED.cultural_element,
    preservation_type = EXCLUDED.preservation_type,
    local_language = EXCLUDED.local_language,
    traditional_practice_summary = EXCLUDED.traditional_practice_summary,
    digital_integration_strategy = EXCLUDED.digital_integration_strategy,
    consent_protocol = EXCLUDED.consent_protocol,
    local_reviewer_role = EXCLUDED.local_reviewer_role,
    implementation_status = EXCLUDED.implementation_status,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();

INSERT INTO renewable_energy_plan (
    id, location_id, farm_id, plan_date, energy_use_case, renewable_source,
    implementation_status, current_energy_source, planned_capacity_kw,
    estimated_annual_kwh, renewable_share_pct, fossil_displacement_estimate_co2e_tonnes,
    infrastructure_dependencies, maintenance_owner_role, plan_summary, public_summary,
    evidence_maturity, status, metadata, source_system, source_id, source_raw
) VALUES (
    'a0000000-0000-0000-0000-000000001320',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    '2026-03-31',
    'irrigation_and_sensor_support',
    'solar',
    'planned',
    'mixed_grid_and_manual_operations',
    2.5000,
    3600.0000,
    35.0000,
    1.800000,
    ARRAY['solar pump quote', 'battery sizing', 'maintenance training', 'water-system integration'],
    'Operations Guild',
    'Adelphi renewable energy plan proposes solar support for irrigation and sensor infrastructure. It is a planned infrastructure improvement, not an implemented renewable-energy claim.',
    'Adelphi has a planned solar irrigation and sensor-support pathway; renewable share and fossil displacement are conservative estimates pending implementation evidence.',
    3,
    'published',
    '{"implementation_claim":"planned_not_implemented","carbon_claim_boundary":"not a carbon credit claim"}'::jsonb,
    'pilot_seed',
    'adelphi-renewable-energy-solar-2026-03',
    '{"record_type":"renewable_energy_plan","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    plan_date = EXCLUDED.plan_date,
    energy_use_case = EXCLUDED.energy_use_case,
    renewable_source = EXCLUDED.renewable_source,
    implementation_status = EXCLUDED.implementation_status,
    current_energy_source = EXCLUDED.current_energy_source,
    planned_capacity_kw = EXCLUDED.planned_capacity_kw,
    estimated_annual_kwh = EXCLUDED.estimated_annual_kwh,
    renewable_share_pct = EXCLUDED.renewable_share_pct,
    fossil_displacement_estimate_co2e_tonnes = EXCLUDED.fossil_displacement_estimate_co2e_tonnes,
    infrastructure_dependencies = EXCLUDED.infrastructure_dependencies,
    maintenance_owner_role = EXCLUDED.maintenance_owner_role,
    plan_summary = EXCLUDED.plan_summary,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();

INSERT INTO vulnerable_group_access_plan (
    id, location_id, farm_id, plan_date, access_scope, vulnerable_groups,
    access_barriers, accommodations, participation_pathways, accountable_role,
    implementation_status, access_coverage_pct, plan_summary, public_summary,
    evidence_maturity, status, metadata, source_system, source_id, source_raw
) VALUES (
    'a0000000-0000-0000-0000-000000001330',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    '2026-03-31',
    'governance',
    ARRAY['women operators', 'local-language participants', 'disabled participants', 'privacy-sensitive contributors'],
    ARRAY['Spanish-language reporting gaps', 'unclear disability accommodation workflow', 'digital wallet onboarding complexity'],
    ARRAY['Spanish summaries', 'pseudonymous contribution path', 'accessibility review before new dashboards', 'non-wallet participation support'],
    ARRAY['community meeting', 'field-worker assisted reporting', 'public-safe feedback channel'],
    'Community Partnerships Guild',
    'planned',
    50.0000,
    'Adelphi has women-led and local-language evidence, but broader vulnerable-group access needs explicit accommodation workflows before claiming full inclusion.',
    'Adelphi documents planned accommodations for local-language, disabled, privacy-sensitive, and non-wallet participants; this is a planning record, not a completed inclusion claim.',
    3,
    'published',
    '{"privacy_boundary":"group summaries only, no raw protected-class data"}'::jsonb,
    'pilot_seed',
    'adelphi-vulnerable-access-2026-03',
    '{"record_type":"vulnerable_group_access_plan","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    plan_date = EXCLUDED.plan_date,
    access_scope = EXCLUDED.access_scope,
    vulnerable_groups = EXCLUDED.vulnerable_groups,
    access_barriers = EXCLUDED.access_barriers,
    accommodations = EXCLUDED.accommodations,
    participation_pathways = EXCLUDED.participation_pathways,
    accountable_role = EXCLUDED.accountable_role,
    implementation_status = EXCLUDED.implementation_status,
    access_coverage_pct = EXCLUDED.access_coverage_pct,
    plan_summary = EXCLUDED.plan_summary,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();

INSERT INTO foundational_wellbeing_observation (
    id, location_id, farm_id, observation_date, wellbeing_domain, stakeholder_group,
    score_value, count_value, qualitative_signal, source_tables, public_summary,
    evidence_maturity, status, metadata, source_system, source_id, source_raw
) VALUES
(
    'a0000000-0000-0000-0000-000000001340',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    '2026-03-31',
    'dignity',
    'farm_operator',
    7.0000,
    NULL,
    'Operator dignity signal is inferred from public-safe feedback about improved capability, clearer summaries, and visible farm work.',
    ARRAY['wellbeing_metric_observation', 'stakeholder_feedback'],
    'Adelphi operator dignity evidence is positive but early-stage, based on public-safe capability and reporting feedback rather than direct certification.',
    3,
    'published',
    '{"source_wellbeing_metric":"operator_capability_score"}'::jsonb,
    'pilot_seed',
    'adelphi-foundational-dignity-2026-03',
    '{"record_type":"foundational_wellbeing_observation","privacy":"public_summary"}'::jsonb
),
(
    'a0000000-0000-0000-0000-000000001341',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    '2026-03-31',
    'peace',
    'local_resident',
    6.5000,
    NULL,
    'Peace and safety signal is inferred from public-safe trust and privacy-boundary evidence, with no unresolved public harm claim in the seeded record.',
    ARRAY['wellbeing_metric_observation', 'participatory_action_record'],
    'Adelphi peace and safety evidence is cautiously positive and should continue to track unresolved concerns through public-safe review workflows.',
    3,
    'published',
    '{"source_wellbeing_metric":"community_trust_signal"}'::jsonb,
    'pilot_seed',
    'adelphi-foundational-peace-2026-03',
    '{"record_type":"foundational_wellbeing_observation","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    observation_date = EXCLUDED.observation_date,
    wellbeing_domain = EXCLUDED.wellbeing_domain,
    stakeholder_group = EXCLUDED.stakeholder_group,
    score_value = EXCLUDED.score_value,
    count_value = EXCLUDED.count_value,
    qualitative_signal = EXCLUDED.qualitative_signal,
    source_tables = EXCLUDED.source_tables,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();
