-- ============================================================
-- 040_pilot_regenerative_outcomes.sql — Adelphi regenerative outcomes, governance, replication, and stewardship examples
-- ============================================================

INSERT INTO regenerative_outcome_summary (
    id, location_id, farm_id, period_start, period_end, summary_name,
    hectares_restored, baseline_species_count, latest_species_count, species_diversity_delta,
    baseline_soil_carbon_t_ha, latest_soil_carbon_t_ha, soil_carbon_delta_t_ha,
    trees_planted_count, trees_surviving_count, tree_survival_rate_pct,
    regenerative_score, jobs_or_roles_supported_count, training_hours, beneficiary_count,
    evidence_confidence, methodology_summary, public_summary, evidence_maturity, status,
    metadata, source_system, source_id, source_raw
) VALUES (
    'a0000000-0000-0000-0000-000000001400',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    '2025-10-01',
    '2026-03-31',
    'Adelphi Q4-Q1 regenerative outcome summary',
    1.3838,
    8,
    14,
    0.4200,
    32.5000,
    34.1000,
    1.6000,
    154,
    141,
    91.5584,
    78.0000,
    4,
    36.0000,
    12,
    'moderate',
    'Summary consolidates governed pilot records across farm area, species observations, soil/carbon indicators, tree inventory, regenerative checklist, labor/training, and public-safe stakeholder evidence. Values are reviewer-facing signals and should be reconciled with source tables before external certification.',
    'Adelphi reports 1.3838 ha under regenerative stewardship, 154 trees inventoried, 91.6% tree survival signal, positive species and soil-carbon deltas, and moderate-confidence public evidence for social and ecological outcomes.',
    3,
    'published',
    '{"source_tables":["location","species_observation","soil_sample","tree_inventory","regenerative_practice_checklist","labor_event","wellbeing_metric_observation"],"claim_boundary":"grant-facing summary, not external certification"}'::jsonb,
    'pilot_seed',
    'adelphi-regenerative-outcomes-2026-03',
    '{"record_type":"regenerative_outcome_summary","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    period_start = EXCLUDED.period_start,
    period_end = EXCLUDED.period_end,
    summary_name = EXCLUDED.summary_name,
    hectares_restored = EXCLUDED.hectares_restored,
    baseline_species_count = EXCLUDED.baseline_species_count,
    latest_species_count = EXCLUDED.latest_species_count,
    species_diversity_delta = EXCLUDED.species_diversity_delta,
    baseline_soil_carbon_t_ha = EXCLUDED.baseline_soil_carbon_t_ha,
    latest_soil_carbon_t_ha = EXCLUDED.latest_soil_carbon_t_ha,
    soil_carbon_delta_t_ha = EXCLUDED.soil_carbon_delta_t_ha,
    trees_planted_count = EXCLUDED.trees_planted_count,
    trees_surviving_count = EXCLUDED.trees_surviving_count,
    tree_survival_rate_pct = EXCLUDED.tree_survival_rate_pct,
    regenerative_score = EXCLUDED.regenerative_score,
    jobs_or_roles_supported_count = EXCLUDED.jobs_or_roles_supported_count,
    training_hours = EXCLUDED.training_hours,
    beneficiary_count = EXCLUDED.beneficiary_count,
    evidence_confidence = EXCLUDED.evidence_confidence,
    methodology_summary = EXCLUDED.methodology_summary,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();

INSERT INTO community_governance_mechanism (
    id, location_id, farm_id, mechanism_name, governance_level, decision_body,
    decision_method, quorum_rule, voting_or_consensus_rights, community_veto_rights,
    escalation_path, power_distribution_summary, participation_cadence, public_summary,
    evidence_maturity, status, metadata, source_system, source_id, source_raw
) VALUES (
    'a0000000-0000-0000-0000-000000001410',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    'Adelphi farm-to-DAO decision pathway',
    'farm',
    'Farm operators, Community Partnerships Guild, Impact Guild, and DAO treasury reviewers',
    'hybrid',
    'Farm-level operational changes require operator review; DAO-funded changes require published proposal or steward approval path.',
    'Farm operators can raise needs through field notes, participatory actions, or Guild review; DAO treasury execution remains governed through Gnosis/Moloch records.',
    'Community concerns can defer public claims, request rework, or require additional review before publication.',
    'Escalate unresolved issues to Governance Guild or Green Paper publication review before public claims expand.',
    'Power is split between farm operators for local practice decisions, Guilds for evidence/review work, and DAO treasury mechanisms for funded proposals; agents can draft summaries but cannot verify or publish.',
    'monthly',
    'Adelphi uses a hybrid pathway where farm operators raise needs, Guilds coordinate review, and DAO treasury records govern funded actions; public claims remain subject to human review.',
    3,
    'published',
    '{"source_records":["participatory_action_record","dao_proposal","governance_inclusion_observation"],"agent_boundary":"draft_only"}'::jsonb,
    'pilot_seed',
    'adelphi-community-governance-2026-03',
    '{"record_type":"community_governance_mechanism","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    mechanism_name = EXCLUDED.mechanism_name,
    governance_level = EXCLUDED.governance_level,
    decision_body = EXCLUDED.decision_body,
    decision_method = EXCLUDED.decision_method,
    quorum_rule = EXCLUDED.quorum_rule,
    voting_or_consensus_rights = EXCLUDED.voting_or_consensus_rights,
    community_veto_rights = EXCLUDED.community_veto_rights,
    escalation_path = EXCLUDED.escalation_path,
    power_distribution_summary = EXCLUDED.power_distribution_summary,
    participation_cadence = EXCLUDED.participation_cadence,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();

INSERT INTO replication_readiness_assessment (
    id, location_id, assessment_date, target_region, farm_model, readiness_score,
    ecological_prerequisites, cultural_governance_prerequisites, infrastructure_prerequisites,
    barriers, enablers, support_structures, minimum_evidence_maturity, replication_status,
    assessment_summary, public_summary, evidence_maturity, status, metadata
) VALUES (
    'a0000000-0000-0000-0000-000000001420',
    'a0000000-0000-0000-0000-000000000001',
    '2026-03-31',
    'Dominican Republic pilot cluster',
    'blended',
    6.5000,
    ARRAY['local water baseline', 'soil and species baseline', 'context-specific syntropic design', 'published risk register'],
    ARRAY['local-language reporting', 'farm-operator decision pathway', 'community feedback channel', 'public-safe cultural review'],
    ARRAY['nursery/biofactory capability', 'buyer access', 'field-worker onboarding', 'renewable energy plan before higher-scale claims'],
    ARRAY['renewable energy not implemented', 'local-language reviewer coverage incomplete', 'evidence maturity still emerging', 'private capital terms excluded'],
    ARRAY['Adelphi live pilot evidence', 'public dashboards', 'DAO/Guild review path', 'open-source schema and reports'],
    ARRAY['operator playbook', 'risk mitigation register', 'financial sustainability plan', 'GNH/access review before new region claims'],
    3,
    'conditional',
    'Adelphi is conditionally ready for regional pilot replication when localized water/soil baselines, operator governance, public-safe cultural review, and renewable/access plans are documented for the next site.',
    'Adelphi supports conditional replication learning, not unlimited scaling: new sites require local baselines, governance setup, cultural/access review, risk gates, and partner support.',
    3,
    'published',
    '{"claim_boundary":"conditional readiness, not guaranteed replication","source_scaling_roadmap":"a0000000-0000-0000-0000-000000001020"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    assessment_date = EXCLUDED.assessment_date,
    target_region = EXCLUDED.target_region,
    farm_model = EXCLUDED.farm_model,
    readiness_score = EXCLUDED.readiness_score,
    ecological_prerequisites = EXCLUDED.ecological_prerequisites,
    cultural_governance_prerequisites = EXCLUDED.cultural_governance_prerequisites,
    infrastructure_prerequisites = EXCLUDED.infrastructure_prerequisites,
    barriers = EXCLUDED.barriers,
    enablers = EXCLUDED.enablers,
    support_structures = EXCLUDED.support_structures,
    minimum_evidence_maturity = EXCLUDED.minimum_evidence_maturity,
    replication_status = EXCLUDED.replication_status,
    assessment_summary = EXCLUDED.assessment_summary,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();

INSERT INTO adaptive_stewardship_review (
    id, location_id, farm_id, review_date, review_period_start, review_period_end,
    stewardship_scope, review_cadence, trigger_thresholds, observed_triggers,
    corrective_actions, action_completion_pct, responsible_role, funding_continuity_plan,
    next_review_date, review_summary, public_summary, evidence_maturity, status,
    metadata, source_system, source_id, source_raw
) VALUES (
    'a0000000-0000-0000-0000-000000001430',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000010',
    '2026-03-31',
    '2026-01-01',
    '2026-03-31',
    'ecological',
    'quarterly',
    ARRAY['water stress sustained for two reporting periods', 'tree survival below 85%', 'species count decline from baseline', 'unresolved community concern'],
    ARRAY['Spanish reporting gap identified', 'renewable energy remains planned not implemented'],
    ARRAY['publish Spanish operator summaries', 'complete solar irrigation quote', 'continue tree survival survey', 'review community feedback monthly'],
    50.0000,
    'Impact Guild',
    'Use reinvestment target, public-goods allocation, and partner sponsorship only after risk and governance gates are reviewed.',
    '2026-06-30',
    'Quarterly review documents ecological and community triggers, assigns corrective actions, and keeps expansion conditional on evidence maturity and operator feedback.',
    'Adelphi stewardship review is quarterly, with corrective actions for language access, renewable planning, tree survival monitoring, and community feedback before stronger public claims or replication.',
    3,
    'published',
    '{"linked_risk_register":["a0000000-0000-0000-0000-000000001010","a0000000-0000-0000-0000-000000001012"],"claim_boundary":"adaptive management evidence"}'::jsonb,
    'pilot_seed',
    'adelphi-adaptive-stewardship-2026-q1',
    '{"record_type":"adaptive_stewardship_review","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    review_date = EXCLUDED.review_date,
    review_period_start = EXCLUDED.review_period_start,
    review_period_end = EXCLUDED.review_period_end,
    stewardship_scope = EXCLUDED.stewardship_scope,
    review_cadence = EXCLUDED.review_cadence,
    trigger_thresholds = EXCLUDED.trigger_thresholds,
    observed_triggers = EXCLUDED.observed_triggers,
    corrective_actions = EXCLUDED.corrective_actions,
    action_completion_pct = EXCLUDED.action_completion_pct,
    responsible_role = EXCLUDED.responsible_role,
    funding_continuity_plan = EXCLUDED.funding_continuity_plan,
    next_review_date = EXCLUDED.next_review_date,
    review_summary = EXCLUDED.review_summary,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();
