-- ============================================================
-- 041_pilot_open_source_capitalist_scaling.sql — Adelphi scaling economics, barriers, stress tests, and open-source reuse examples
-- ============================================================

INSERT INTO farm_launch_unit_economics (
    id, location_id, source_scaling_milestone_id, economics_name, farm_model,
    target_region, planned_farm_count, planned_hectares, expected_beneficiary_count,
    setup_cost_usd, first_year_operating_cost_usd, verification_overhead_usd,
    total_launch_cost_usd, cost_per_farm_usd, cost_per_hectare_usd,
    cost_per_beneficiary_usd, projected_annual_revenue_usd, projected_annual_noi_usd,
    projected_roi_pct, payback_months, launch_timeline_months, assumptions,
    evidence_confidence, public_summary, evidence_maturity, status, metadata,
    source_system, source_id, source_raw
) VALUES (
    'a0000000-0000-0000-0000-000000001500',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000001020',
    'Adelphi two-farm replication unit economics',
    'blended',
    'Dominican Republic pilot cluster',
    2,
    2.7676,
    24,
    24500.00,
    30600.00,
    4900.00,
    60000.00,
    30000.00,
    21679.43,
    2500.00,
    49000.00,
    18400.00,
    30.6667,
    39.13,
    12.00,
    ARRAY['Uses Adelphi public financial plan as unit baseline', 'Two-farm target is planned/conditional, not already operating', 'Verification overhead estimated at 10% of launch capital', 'Beneficiary count uses aggregate public-safe estimate only'],
    'moderate',
    'Adelphi two-farm replication economics estimate $60k total launch cost, $30k per planned farm, $2.5k per aggregate beneficiary, and 30.7% projected ROI under planning assumptions; this is not a guaranteed return or live-farm claim.',
    3,
    'published',
    '{"source_plan_id":"a0000000-0000-0000-0000-000000001000","source_scaling_milestone_id":"a0000000-0000-0000-0000-000000001020","claim_boundary":"planned conditional unit economics, not already operating farms"}'::jsonb,
    'pilot_seed',
    'adelphi-two-farm-unit-economics-2026',
    '{"record_type":"farm_launch_unit_economics","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    source_scaling_milestone_id = EXCLUDED.source_scaling_milestone_id,
    economics_name = EXCLUDED.economics_name,
    farm_model = EXCLUDED.farm_model,
    target_region = EXCLUDED.target_region,
    planned_farm_count = EXCLUDED.planned_farm_count,
    planned_hectares = EXCLUDED.planned_hectares,
    expected_beneficiary_count = EXCLUDED.expected_beneficiary_count,
    setup_cost_usd = EXCLUDED.setup_cost_usd,
    first_year_operating_cost_usd = EXCLUDED.first_year_operating_cost_usd,
    verification_overhead_usd = EXCLUDED.verification_overhead_usd,
    total_launch_cost_usd = EXCLUDED.total_launch_cost_usd,
    cost_per_farm_usd = EXCLUDED.cost_per_farm_usd,
    cost_per_hectare_usd = EXCLUDED.cost_per_hectare_usd,
    cost_per_beneficiary_usd = EXCLUDED.cost_per_beneficiary_usd,
    projected_annual_revenue_usd = EXCLUDED.projected_annual_revenue_usd,
    projected_annual_noi_usd = EXCLUDED.projected_annual_noi_usd,
    projected_roi_pct = EXCLUDED.projected_roi_pct,
    payback_months = EXCLUDED.payback_months,
    launch_timeline_months = EXCLUDED.launch_timeline_months,
    assumptions = EXCLUDED.assumptions,
    evidence_confidence = EXCLUDED.evidence_confidence,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();

INSERT INTO network_scaling_target (
    id, target_name, target_region, farm_model, target_date, target_farm_count,
    target_hectares, target_beneficiary_count, capital_required_usd,
    expected_public_goods_value_usd, expected_verification_outputs, readiness_score,
    dependency_summary, risk_gate_summary, target_status, public_summary,
    evidence_maturity, status, metadata
) VALUES
(
    'a0000000-0000-0000-0000-000000001510',
    'Dominican two-farm pilot cluster target',
    'Dominican Republic pilot cluster',
    'blended',
    '2026-12-31',
    2,
    2.7676,
    24,
    60000.00,
    4900.00,
    12,
    6.5000,
    'Requires local buyer agreements, agronomy advisor coverage, operator onboarding, impact verification partner, and public-safe Spanish summaries.',
    'Launch remains conditional on runway >= 6 months, risk mitigation coverage, public evidence maturity, and local operator governance.',
    'conditional',
    'The Dominican two-farm pilot target is a conditional roadmap target with $60k estimated launch capital and 6.5/10 readiness; it is not evidence of two already-operating farms.',
    3,
    'published',
    '{"source_scaling_milestone_id":"a0000000-0000-0000-0000-000000001020","claim_boundary":"planned target, not live farm count"}'::jsonb
),
(
    'a0000000-0000-0000-0000-000000001511',
    'Public-goods four-farm playbook target',
    'Celo/Gnosis aligned ReFi partner network',
    'public_good_optimized',
    '2027-06-30',
    4,
    5.5352,
    48,
    120000.00,
    9800.00,
    24,
    5.5000,
    'Requires Green Paper publication, local cooperative partner, open-source operator playbook, CIDS-compatible reporting, and recurring public dashboard evidence.',
    'Launch remains conditional on publication review, grant dependency reduction, community feedback loops, and farm-by-farm registry records.',
    'planned',
    'The four-farm playbook is a planned replication target for review, with $120k estimated launch capital and unresolved dependency gates before public expansion claims.',
    3,
    'published',
    '{"source_scaling_milestone_id":"a0000000-0000-0000-0000-000000001021","claim_boundary":"planned pipeline, not already operating farms"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    target_name = EXCLUDED.target_name,
    target_region = EXCLUDED.target_region,
    farm_model = EXCLUDED.farm_model,
    target_date = EXCLUDED.target_date,
    target_farm_count = EXCLUDED.target_farm_count,
    target_hectares = EXCLUDED.target_hectares,
    target_beneficiary_count = EXCLUDED.target_beneficiary_count,
    capital_required_usd = EXCLUDED.capital_required_usd,
    expected_public_goods_value_usd = EXCLUDED.expected_public_goods_value_usd,
    expected_verification_outputs = EXCLUDED.expected_verification_outputs,
    readiness_score = EXCLUDED.readiness_score,
    dependency_summary = EXCLUDED.dependency_summary,
    risk_gate_summary = EXCLUDED.risk_gate_summary,
    target_status = EXCLUDED.target_status,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();

INSERT INTO adoption_barrier_assessment (
    id, location_id, assessment_date, barrier_category, barrier_name,
    affected_scope, severity, likelihood, resolution_status, owner_role,
    mitigation_plan, estimated_mitigation_cost_usd, target_resolution_date,
    public_summary, evidence_maturity, status, metadata, source_system, source_id, source_raw
) VALUES
(
    'a0000000-0000-0000-0000-000000001520',
    'a0000000-0000-0000-0000-000000000001',
    '2026-03-31',
    'farmer_onboarding',
    'Operator onboarding and reporting load for new pilot farms',
    'region',
    'medium',
    'medium',
    'mitigating',
    'Community Partnerships Guild',
    'Use spreadsheet bridge, Spanish public summaries, operator playbook, and monthly steward review before adding new farms.',
    3000.00,
    '2026-09-30',
    'New farm onboarding needs operator training, local-language support, and simple reporting tools before the two-farm pilot target advances.',
    3,
    'published',
    '{"source_records":["spreadsheet_bridge","holistic_wellbeing","scaling_roadmap"],"privacy":"group_summary_only"}'::jsonb,
    'pilot_seed',
    'adelphi-adoption-operator-onboarding-2026',
    '{"record_type":"adoption_barrier_assessment","privacy":"public_summary"}'::jsonb
),
(
    'a0000000-0000-0000-0000-000000001521',
    'a0000000-0000-0000-0000-000000000001',
    '2026-03-31',
    'regulatory',
    'Local permitting and farm registry requirements vary by new site',
    'region',
    'medium',
    'unknown',
    'open',
    'Governance Guild',
    'Require site-by-site registry, local advisor review, and publication gate before claiming expansion readiness.',
    2500.00,
    '2026-10-31',
    'Regulatory readiness is unresolved for new sites and must be reviewed locally before public expansion commitments are made.',
    3,
    'published',
    '{"claim_boundary":"regulatory review required per site"}'::jsonb,
    'pilot_seed',
    'adelphi-adoption-regulatory-2026',
    '{"record_type":"adoption_barrier_assessment","privacy":"public_summary"}'::jsonb
),
(
    'a0000000-0000-0000-0000-000000001522',
    'a0000000-0000-0000-0000-000000000001',
    '2026-03-31',
    'dao_governance',
    'DAO and co-op decision paths need local comprehension and dispute handling',
    'community',
    'medium',
    'medium',
    'mitigating',
    'Governance Guild',
    'Publish plain-language governance summaries, escalation paths, and human approval gates; keep agents draft-only.',
    1800.00,
    '2026-08-31',
    'DAO/co-op adoption requires local-language governance summaries and clear human escalation paths before broader rollout.',
    3,
    'published',
    '{"source_record":"adelphi-community-governance-2026-03","agent_boundary":"draft_only"}'::jsonb,
    'pilot_seed',
    'adelphi-adoption-dao-governance-2026',
    '{"record_type":"adoption_barrier_assessment","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    assessment_date = EXCLUDED.assessment_date,
    barrier_category = EXCLUDED.barrier_category,
    barrier_name = EXCLUDED.barrier_name,
    affected_scope = EXCLUDED.affected_scope,
    severity = EXCLUDED.severity,
    likelihood = EXCLUDED.likelihood,
    resolution_status = EXCLUDED.resolution_status,
    owner_role = EXCLUDED.owner_role,
    mitigation_plan = EXCLUDED.mitigation_plan,
    estimated_mitigation_cost_usd = EXCLUDED.estimated_mitigation_cost_usd,
    target_resolution_date = EXCLUDED.target_resolution_date,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();

INSERT INTO perpetual_value_stress_test (
    id, location_id, financial_sustainability_plan_id, scenario_name, scenario_date,
    stress_type, revenue_change_pct, cost_change_pct, grant_delay_months,
    yield_change_pct, baseline_runway_months, downside_runway_months,
    baseline_noi_usd, downside_noi_usd, solvency_status, mitigation_actions,
    public_summary, evidence_maturity, status, metadata, source_system, source_id, source_raw
) VALUES
(
    'a0000000-0000-0000-0000-000000001530',
    'a0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000001000',
    'Adelphi combined downside operating stress',
    '2026-03-31',
    'combined_downside',
    -25.0000,
    15.0000,
    3.0000,
    -20.0000,
    9.5000,
    5.2000,
    9200.00,
    50.00,
    'needs_mitigation',
    ARRAY['defer nonessential expansion', 'prioritize crop mix with confirmed buyers', 'draw on public-goods sponsor pipeline only after governance approval', 'review insurance and water resilience before next season'],
    'A combined downside case with lower revenue, higher costs, yield shock, and grant delay leaves Adelphi above zero NOI but reduces runway to 5.2 months, so expansion should remain conditional.',
    3,
    'published',
    '{"source_plan_id":"a0000000-0000-0000-0000-000000001000","stress_boundary":"planning evidence, not guarantee of solvency"}'::jsonb,
    'pilot_seed',
    'adelphi-combined-downside-stress-2026',
    '{"record_type":"perpetual_value_stress_test","privacy":"public_summary"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    financial_sustainability_plan_id = EXCLUDED.financial_sustainability_plan_id,
    scenario_name = EXCLUDED.scenario_name,
    scenario_date = EXCLUDED.scenario_date,
    stress_type = EXCLUDED.stress_type,
    revenue_change_pct = EXCLUDED.revenue_change_pct,
    cost_change_pct = EXCLUDED.cost_change_pct,
    grant_delay_months = EXCLUDED.grant_delay_months,
    yield_change_pct = EXCLUDED.yield_change_pct,
    baseline_runway_months = EXCLUDED.baseline_runway_months,
    downside_runway_months = EXCLUDED.downside_runway_months,
    baseline_noi_usd = EXCLUDED.baseline_noi_usd,
    downside_noi_usd = EXCLUDED.downside_noi_usd,
    solvency_status = EXCLUDED.solvency_status,
    mitigation_actions = EXCLUDED.mitigation_actions,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    source_system = EXCLUDED.source_system,
    source_id = EXCLUDED.source_id,
    source_raw = EXCLUDED.source_raw,
    updated_at = NOW();

INSERT INTO open_source_impact_artifact (
    id, artifact_name, artifact_type, repository_path, external_url, license,
    version, reuse_status, reuse_count, supported_use_cases, verification_outputs,
    maintenance_owner, public_summary, evidence_maturity, status, metadata
) VALUES
(
    'a0000000-0000-0000-0000-000000001540',
    'Kokonut governed PostgreSQL schemas',
    'schema',
    'schemas/postgres/',
    NULL,
    'repo_license',
    'v2026.06',
    'in_use',
    1,
    ARRAY['farm operations', 'financial sustainability', 'regenerative outcomes', 'public-safe reporting'],
    ARRAY['public views', 'report snapshots', 'CIDS export', 'EAS attestation metadata'],
    'Technology Guild',
    'The governed PostgreSQL schema layer is reusable infrastructure for farm evidence, metrics, public views, and report generation.',
    3,
    'published',
    '{"claim_boundary":"internal reuse evidenced; external reuse not claimed without source"}'::jsonb
),
(
    'a0000000-0000-0000-0000-000000001541',
    'Public-safe Metabase dashboard pack',
    'dashboard',
    'dashboards/metabase/',
    NULL,
    'repo_license',
    'v2026.06',
    'in_use',
    1,
    ARRAY['impact review', 'financial review', 'scaling review', 'evidence gap review'],
    ARRAY['dashboard_dataset rows', 'SQL dashboard queries'],
    'Technology Guild',
    'The dashboard pack turns governed public views into reusable reviewer dashboards without exposing private stakeholder data.',
    3,
    'published',
    '{"privacy":"public_safe"}'::jsonb
),
(
    'a0000000-0000-0000-0000-000000001542',
    'CIDS Essential Tier export mapping',
    'export_mapping',
    'services/registry/cids_export.py',
    NULL,
    'repo_license',
    'v3.2.0',
    'in_use',
    1,
    ARRAY['CIDS compatibility', 'public impact reporting', 'grant evidence export'],
    ARRAY['CIDS IndicatorReport', 'public metric views'],
    'Impact Guild',
    'The CIDS exporter maps canonical PostgreSQL evidence to CIDS-compatible public reporting outputs.',
    3,
    'published',
    '{"cids_version":"3.2.0","claim_boundary":"compatibility export, not external certification"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    artifact_name = EXCLUDED.artifact_name,
    artifact_type = EXCLUDED.artifact_type,
    repository_path = EXCLUDED.repository_path,
    external_url = EXCLUDED.external_url,
    license = EXCLUDED.license,
    version = EXCLUDED.version,
    reuse_status = EXCLUDED.reuse_status,
    reuse_count = EXCLUDED.reuse_count,
    supported_use_cases = EXCLUDED.supported_use_cases,
    verification_outputs = EXCLUDED.verification_outputs,
    maintenance_owner = EXCLUDED.maintenance_owner,
    public_summary = EXCLUDED.public_summary,
    evidence_maturity = EXCLUDED.evidence_maturity,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();
