-- ============================================================
-- 044_bio_factory_operations.sql — Reference data: metrics, dashboards, composition matrix, LAC regional inputs
-- ============================================================

INSERT INTO metric_definition (
    metric_key, display_name, description, formula, source_tables, inclusion_rules,
    exclusion_rules, unit, data_type, owner, version, update_frequency, active,
    validation_tests, report_usage, deprecation_policy
) VALUES
('bio_batch_yield_pct', 'Bio Batch Yield %', 'Output kg recovered per input kg for a bio-factory production batch.', '(output_kg_total / input_kg_total) * 100', ARRAY['bio_factory_batch'], 'Use reviewed batches with documented input and output weights.', 'Exclude draft batches and unverified yield claims.', 'percentage', 'numeric', 'Operations Guild', 1, 'quarterly', TRUE, '["0 <= value <= 200", "input_kg_total > 0"]'::jsonb, ARRAY['bio_factory_batch', 'green_paper'], 'Supersede through metric_version before changing public interpretation.'),
('bio_input_provenance_rate_pct', 'Input Provenance Verification Rate %', 'Share of input records with supplier_verified = TRUE.', 'verified_count / total_count * 100', ARRAY['bio_input_provenance'], 'Use published input records with supplier_verified flagged.', 'Exclude private supplier terms and unverified supplier names.', 'percentage', 'numeric', 'Operations Guild', 1, 'quarterly', TRUE, '["0 <= value <= 100", "total_count > 0"]'::jsonb, ARRAY['bio_input_provenance', 'green_paper'], 'Supersede through metric_version before changing public interpretation.'),
('bio_recipe_reuse_count', 'Recipe Reuse Count', 'Number of bio_factory_batch records referencing the same recipe.', 'count(bio_factory_batch where recipe_id = X)', ARRAY['bio_factory_batch', 'bio_recipe_library'], 'Use published batches with a documented recipe reference.', 'Exclude draft or one-off recipes that have not been reproduced.', 'count', 'integer', 'Operations Guild', 1, 'quarterly', TRUE, '["value >= 0"]'::jsonb, ARRAY['bio_recipe_library', 'green_paper'], 'Supersede through metric_version before changing public interpretation.'),
('bio_quality_test_pass_rate_pct', 'Bio Quality Test Pass Rate %', 'Share of quality tests where pass_fail = pass.', 'pass_count / total_count * 100', ARRAY['bio_factory_quality_test'], 'Use reviewed tests with documented measured values.', 'Exclude pending or unverified test results.', 'percentage', 'numeric', 'Operations Guild', 1, 'quarterly', TRUE, '["0 <= value <= 100", "total_count > 0"]'::jsonb, ARRAY['bio_quality_test', 'green_paper'], 'Supersede through metric_version before changing public interpretation.'),
('bio_distribution_recipient_count', 'Bio Distribution Recipient Count', 'Unique recipient names across published bio_factory_distribution records.', 'count(DISTINCT recipient_name)', ARRAY['bio_factory_distribution'], 'Use published distribution records.', 'Exclude private recipient identities where consent is not given.', 'count', 'integer', 'Operations Guild', 1, 'quarterly', TRUE, '["value >= 0"]'::jsonb, ARRAY['bio_factory_distribution', 'green_paper'], 'Supersede through metric_version before changing public interpretation.'),
('bio_lac_input_share_pct', 'LAC Regional Input Share %', 'Share of bio_input_provenance records with origin_region in Latin America or the Caribbean.', 'lac_count / total_count * 100', ARRAY['bio_input_provenance'], 'Use published inputs with origin_country and origin_region populated.', 'Exclude records without geographic provenance.', 'percentage', 'numeric', 'Operations Guild', 1, 'quarterly', TRUE, '["0 <= value <= 100", "total_count > 0"]'::jsonb, ARRAY['bio_input_provenance', 'bio_regional_input', 'green_paper'], 'Supersede through metric_version before changing public interpretation.')
ON CONFLICT (metric_key) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    formula = EXCLUDED.formula,
    source_tables = EXCLUDED.source_tables,
    inclusion_rules = EXCLUDED.inclusion_rules,
    exclusion_rules = EXCLUDED.exclusion_rules,
    unit = EXCLUDED.unit,
    data_type = EXCLUDED.data_type,
    owner = EXCLUDED.owner,
    update_frequency = EXCLUDED.update_frequency,
    active = EXCLUDED.active,
    validation_tests = EXCLUDED.validation_tests,
    report_usage = EXCLUDED.report_usage,
    deprecation_policy = EXCLUDED.deprecation_policy;

INSERT INTO dashboard_dataset (
    id, name, description, dataset_type, location_id, query_sql, refresh_interval_minutes, status, metadata
) VALUES
('a0000000-0000-0000-0000-000000003801', 'Bio Factory Batches', 'Public-safe bio-organic fertilizer production batches for Latin America and the Caribbean.', 'bio_factory_batch', NULL, 'dashboards/metabase/sql/57_bio_factory_batches.sql', 1440, 'published', '{"owner":"operations_guild","refresh_cron":"0 6 * * *","privacy":"public_safe"}'::jsonb),
('a0000000-0000-0000-0000-000000003802', 'Bio Input Provenance', 'Public-safe ingredient sourcing with LAC regional focus and quality warnings.', 'bio_input_provenance', NULL, 'dashboards/metabase/sql/58_input_provenance.sql', 1440, 'published', '{"owner":"operations_guild","refresh_cron":"0 6 * * *","privacy":"public_safe"}'::jsonb),
('a0000000-0000-0000-0000-000000003803', 'Bio Recipe Library', 'Public-safe bio-organic fertilizer recipes with ingredients, ratios, and process steps.', 'bio_recipe_library', NULL, 'dashboards/metabase/sql/59_recipe_library.sql', 1440, 'published', '{"owner":"operations_guild","refresh_cron":"0 6 * * *","privacy":"public_safe"}'::jsonb),
('a0000000-0000-0000-0000-000000003804', 'Bio Quality & Distribution', 'Public-safe quality test results and distribution tracking.', 'bio_quality_distribution', NULL, 'dashboards/metabase/sql/60_quality_distribution.sql', 1440, 'published', '{"owner":"operations_guild","refresh_cron":"0 6 * * *","privacy":"public_safe"}'::jsonb),
('a0000000-0000-0000-0000-000000003805', 'Bio LAC Regional Inputs', 'Public-safe LAC regional input availability for bio-organic fertilizer production.', 'bio_regional_input', NULL, 'dashboards/metabase/sql/61_regional_inputs.sql', 1440, 'published', '{"owner":"operations_guild","refresh_cron":"0 6 * * *","privacy":"public_safe"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    dataset_type = EXCLUDED.dataset_type,
    query_sql = EXCLUDED.query_sql,
    refresh_interval_minutes = EXCLUDED.refresh_interval_minutes,
    status = EXCLUDED.status,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();

INSERT INTO bio_ingredient_composition_reference (
    ingredient_name, ingredient_category, n_pct_min, n_pct_typical, n_pct_max,
    p_pct_min, p_pct_typical, p_pct_max, k_pct_min, k_pct_typical, k_pct_max,
    micronutrients, typical_source, state, composition_summary, public_summary, source_reference
) VALUES
('Bone meal', 'animal_concentrate', 3.0, 4.5, 6.0, 12.0, 21.0, 30.0, 0.0, 0.0, 0.0, '{"Ca": "high", "P2O5": "12-30%"}', 'Slaughterhouse byproducts (steamed and ground bones)', 'solid', 'High-phosphorus slow-release amendment. Steamed bone meal is safer than raw bone meal (pathogen risk).', 'Bone meal: ~4.5% N, ~21% P, 0% K on a dry-weight basis. Slow-release phosphorus source. Typical application: side-dress at planting.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('Blood meal', 'animal_concentrate', 10.0, 12.0, 14.0, 0.0, 1.0, 2.0, 0.0, 0.5, 1.0, '{"Fe": "moderate"}', 'Slaughterhouse byproducts (dried blood)', 'solid', 'High-nitrogen fast-release amendment. Apply carefully to avoid burning plants.', 'Blood meal: ~12% N, ~1% P, ~0.5% K. High-nitrogen fast-release source. Use sparingly; can burn plants if over-applied.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('Feather meal', 'animal_concentrate', 10.0, 12.0, 14.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, '{}', 'Poultry processing (hydrolyzed feathers)', 'solid', 'Very high nitrogen, negligible P and K. Slow-release; benefits from soil microbial activity.', 'Feather meal: ~12% N, 0% P, 0% K. Slow-release nitrogen source; needs microbial breakdown to become plant-available.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('Poultry manure (chicken)', 'animal_manure', 3.0, 3.5, 4.0, 1.0, 1.5, 2.0, 1.0, 1.5, 2.0, '{"Ca": "moderate", "Mg": "low"}', 'Poultry farming (fresh or composted)', 'solid', 'Richest common manure. Often composted/aged to reduce pathogens and ammonia.', 'Poultry manure: ~3.5% N, ~1.5% P, ~1.5% K. Richest common manure. Compost 6-12 months to reduce pathogens before application.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('Cattle manure (cow)', 'animal_manure', 2.0, 2.5, 3.0, 0.5, 0.75, 1.0, 1.0, 1.5, 2.0, '{"Ca": "moderate"}', 'Cattle farming (slurry or solid, often composted)', 'solid', 'Balanced manure. Lower N than poultry but adds organic matter.', 'Cattle manure: ~2.5% N, ~0.75% P, ~1.5% K. Balanced manure. Often composted with straw before application.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('Swine manure (pig)', 'animal_manure', 2.0, 3.0, 4.0, 0.5, 1.0, 2.0, 1.0, 1.5, 2.5, '{}', 'Pig farming (slurry or solid, often composted)', 'solid', 'Higher N than cattle but can contain pathogens. Compost thoroughly.', 'Swine manure: ~3% N, ~1% P, ~1.5% K. Higher nitrogen than cattle manure. Must be composted to reduce pathogen risk.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('Alfalfa meal', 'plant_meal', 2.5, 3.0, 3.5, 0.5, 1.0, 1.5, 1.5, 2.0, 2.5, '{"Ca": "moderate", "Mg": "low"}', 'Dried and ground alfalfa hay', 'solid', 'Moderate nitrogen with slow-release. Adds organic matter and trace minerals.', 'Alfalfa meal: ~3% N, ~1% P, ~2% K. Slow-release organic nitrogen with trace minerals. Also contains triacontanol, a natural growth stimulant.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('Cottonseed meal', 'plant_meal', 4.0, 6.0, 7.0, 1.0, 2.5, 3.0, 1.0, 1.5, 2.0, '{}', 'Cotton processing byproducts (ground)', 'solid', 'High nitrogen slow-release amendment. Acidic effect on soil.', 'Cottonseed meal: ~6% N, ~2.5% P, ~1.5% K. High-nitrogen slow-release amendment. Slightly acidic; good for acid-loving plants.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('Neem cake', 'plant_meal', 4.0, 5.0, 6.0, 0.5, 1.0, 1.5, 1.0, 1.5, 2.0, '{}', 'Neem seed processing byproduct (oil-extracted cake)', 'solid', 'Nitrogen source with natural pest-repellent properties (azadirachtin).', 'Neem cake: ~5% N, ~1% P, ~1.5% K. Slow-release nitrogen with natural nematicide and pest-repellent properties. Common in tropical agriculture.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('Kelp meal (Ascophyllum)', 'marine_material', 1.0, 1.25, 1.5, 0.5, 0.75, 1.0, 5.0, 7.5, 10.0, '{"I": "moderate", "Fe": "moderate", "Mg": "moderate", "Mn": "moderate", "Zn": "low"}', 'Dried and ground brown algae (kelp)', 'solid', 'High potassium with broad micronutrient profile. Contains natural growth hormones.', 'Kelp meal: ~1.25% N, ~0.75% P, ~7.5% K. High potassium with broad micronutrients (I, Fe, Mg, Mn, Zn) and natural cytokinins and auxins. Slow-release.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('Sargassum (Caribbean)', 'marine_material', 0.5, 1.0, 1.5, 0.1, 0.3, 0.5, 3.0, 5.0, 7.0, '{"Fe": "high", "Mg": "moderate", "Ca": "moderate", "I": "moderate"}', 'Caribbean sargassum seaweed (washed and processed)', 'solid', 'High potassium with minerals and plant hormones. Requires washing to remove salts and arsenic.', 'Sargassum: ~1% N, ~0.3% P, ~5% K on dry-weight basis. High K, Fe, Mg, Ca, I. Contains natural growth hormones. WARNING: untreated sargassum may contain salts and arsenic; washing and controlled extraction required.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research); Caribbean biofertilizer initiatives (Red Diamond Compost)'),
('Vermicompost (worm castings)', 'compost', 1.0, 1.5, 2.0, 0.5, 1.0, 1.5, 1.0, 1.5, 2.0, '{"Ca": "moderate", "Mg": "moderate", "humic_acids": "high"}', 'Kitchen/garden waste processed by Eisenia fetida (red wigglers)', 'solid', 'Balanced compost with high microbial activity and humic acid content.', 'Vermicompost: ~1.5% N, ~1% P, ~1.5% K. Balanced with high microbial activity and humic acids. Excellent soil conditioner.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('Aerobic compost (mixed)', 'compost', 1.0, 2.0, 3.0, 0.5, 1.0, 2.0, 1.0, 1.5, 2.0, '{}', 'Mixed organic waste (greens + browns at ~30:1 C:N)', 'solid', 'Variable composition. Depends on feedstock mix and composting process.', 'Aerobic compost: ~2% N, ~1% P, ~1.5% K typical. Composition varies with feedstock. Made by mixing greens (N-rich) with browns (C-rich) at ~30:1 C:N, maintaining ~50-60% moisture and aeration.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('Compost tea (aerated)', 'compost', 0.05, 0.2, 0.5, 0.05, 0.2, 0.5, 0.1, 0.3, 0.5, '{}', 'Aerated brew of mature compost (10% w/v) steeped 24-72 hours', 'liquid', 'Very dilute. Provides soluble nutrients and beneficial microbes for foliar/soil application.', 'Compost tea: ~0.1-0.5% NPK. Very dilute liquid from aerated mature compost (10% w/v, 24-72 hours). Supplies soluble nutrients and beneficial microbes.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('Fish emulsion (fermented)', 'animal_concentrate', 3.0, 4.5, 5.0, 0.5, 1.0, 1.5, 0.0, 0.5, 1.0, '{"Ca": "low", "amino_acids": "high"}', 'Fermented fish scraps with molasses/sawdust (4 weeks anaerobic)', 'liquid', 'Liquid NPK with amino acids. Dilute 1:5-10 for application.', 'Fish emulsion: ~4-5% N, ~1% P, ~0.5% K. Fermented fish scraps (e.g. 2 kg fish + 2 lb sawdust + 2 Tbsp molasses, 4 weeks anaerobic). Dilute 1:5-10 for use.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('Seaweed extract (kelp tea)', 'marine_material', 0.05, 0.2, 0.5, 0.02, 0.1, 0.2, 0.5, 1.5, 3.0, '{"I": "moderate", "Fe": "low", "Mg": "low", "growth_hormones": "moderate"}', 'Dried kelp or sargassum soaked in water (1/4 cup per gallon, 2-3 days)', 'liquid', 'Low NPK but high K and growth hormones. Dilute 1:10 for foliar spray.', 'Seaweed extract: low NPK, high K (~0.5-3%), with I, Fe, Mg, and natural growth hormones. Made by steeping dried kelp meal (1/4 cup per gallon, 2-3 days). Dilute 1:10 for foliar application.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('Manure tea', 'animal_manure', 0.05, 0.2, 0.5, 0.02, 0.1, 0.2, 0.1, 0.3, 0.5, '{}', 'Aged manure soaked in water with optional molasses (1-2 weeks)', 'liquid', 'Dilute liquid form of manure. Provides soluble nutrients and microbes.', 'Manure tea: dilute form of manure NPK. Made by soaking aged manure (~10% w/v) in water 1-2 weeks, then straining. Optional molasses adds energy for microbial activity.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('Green manure (legume cover crop)', 'plant_meal', 2.0, 3.0, 4.0, 0.0, 0.25, 0.5, 1.0, 2.0, 3.0, '{"N_fixing": "yes"}', 'Legume cover crops (sunn hemp, sesbania, cowpea) tilled in at flowering', 'solid', 'N-rich organic matter. Nitrogen-fixing legumes enrich soil when tilled in before seed set.', 'Green manure: ~3% N, ~0.25% P, ~2% K. Legume cover crops (sunn hemp, sesbania, cowpea) tilled in at flowering enrich soil with nitrogen and organic matter. N-fixing bacteria in root nodules contribute N.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('Humic acid (leonardite)', 'mineral_amendment', 0.0, 0.5, 1.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.5, '{"humic_acids": "very_high", "fulvic_acids": "moderate"}', 'Leonardite or peat processed into soluble humic substances', 'solid', 'Soil conditioner with high humic acid content. Improves soil structure and cation exchange.', 'Humic acid (leonardite): low NPK but very high humic acid content. Soil conditioner that improves soil structure, water retention, and cation exchange capacity. Not measured as NPK.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)')
ON CONFLICT (ingredient_name) DO UPDATE SET
    ingredient_category = EXCLUDED.ingredient_category,
    n_pct_min = EXCLUDED.n_pct_min,
    n_pct_typical = EXCLUDED.n_pct_typical,
    n_pct_max = EXCLUDED.n_pct_max,
    p_pct_min = EXCLUDED.p_pct_min,
    p_pct_typical = EXCLUDED.p_pct_typical,
    p_pct_max = EXCLUDED.p_pct_max,
    k_pct_min = EXCLUDED.k_pct_min,
    k_pct_typical = EXCLUDED.k_pct_typical,
    k_pct_max = EXCLUDED.k_pct_max,
    micronutrients = EXCLUDED.micronutrients,
    typical_source = EXCLUDED.typical_source,
    state = EXCLUDED.state,
    composition_summary = EXCLUDED.composition_summary,
    public_summary = EXCLUDED.public_summary,
    source_reference = EXCLUDED.source_reference,
    updated_at = NOW();

INSERT INTO bio_regional_input_availability (
    region_scope, input_name, input_category, country, subregion, seasonality,
    sourcing_notes, cautions, quality_considerations, typical_suppliers,
    regional_summary, public_summary, source_reference
) VALUES
('caribbean', 'Sargassum seaweed', 'marine_material', 'Caribbean region', 'Caribbean Sargassum Belt (Greater Antilles)', 'Year-round peaks (typically spring/summer)', 'Inundating sargassum blooms in the Caribbean Sargassum Belt. Collected from beaches and offshore. Companies like Red Diamond Compost produce "Supreme Sea" extract.', ARRAY['Untreated sargassum may contain salts and arsenic', 'Requires washing and controlled extraction', 'Heavy metal contamination possible from ocean pollution'], 'Washed and processed sargassum is high in K, Fe, Mg, Ca, and I, plus natural growth hormones. Companies like Red Diamond Compost produce sargassum extract ("Supreme Sea") with post-extraction biomass composted into humus.', 'Caribbean sargassum processors (e.g., Red Diamond Compost, Sargassum Watch contributors)', 'Sargassum is an abundant Caribbean marine biomass usable for biofertilizer and biostimulant production. CAUTION: requires washing to remove salts and arsenic; controlled extraction preserves beneficial hormones and minerals.', 'Sargassum is a Caribbean marine material usable for bio-organic fertilizer and biostimulant production. Washing and controlled extraction required. Suppliers: Caribbean sargassum processors including Red Diamond Compost ("Supreme Sea" extract).', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research); Caribbean biofertilizer initiatives'),
('caribbean', 'Cocoa pod husks', 'agricultural_byproduct', 'Dominican Republic, Haiti, Trinidad', 'Greater Antilles and Caribbean cocoa-growing regions', 'Year-round peaks (harvest seasons)', 'Abundant byproduct from cocoa processing. Can be composted or used as mulch.', ARRAY['May contain pesticide residues from cocoa farming', 'Tannins can inhibit germination if used raw'], 'Cocoa pod husks are high in fiber and moderate in K. Best composted before use. Some cocoa farms use organic certification (verify supplier claims).', 'Caribbean cocoa cooperatives and processors', 'Cocoa pod husks are an abundant Caribbean agricultural byproduct. Best composted before application due to tannin content and potential pesticide residues.', 'Cocoa pod husks: Caribbean agricultural byproduct, abundant in cocoa-growing regions. CAUTION: may contain pesticide residues; tannins can inhibit germination if used raw. Best composted before application.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('caribbean', 'Banana residues', 'agricultural_byproduct', 'Dominican Republic, Costa Rica, Ecuador', 'Caribbean and Central American banana-growing regions', 'Year-round', 'Banana stems, leaves, and rejected fruit. High in K and organic matter. Vermicomposting works well.', ARRAY['May contain fungicide residues from banana farming', 'High moisture content requires careful composting'], 'Banana residues are high in K and organic matter. Vermicomposting with Eisenia fetida produces excellent worm castings from banana waste. Some farms use organic certification.', 'Caribbean and Central American banana cooperatives', 'Banana residues (stems, leaves, rejected fruit) are an abundant Caribbean/Central American agricultural byproduct. High in K; vermicomposting recommended for best results.', 'Banana residues: Caribbean agricultural byproduct, high in K. CAUTION: may contain fungicide residues; high moisture requires careful composting. Vermicomposting with red wigglers produces excellent castings.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('central_america', 'Coffee pulp', 'agricultural_byproduct', 'Honduras, Guatemala, Costa Rica, Nicaragua', 'Central American coffee belt', 'Harvest season (typically October-March)', 'Coffee pulp (cherry skin and mucilage) is abundant during coffee processing. High in N and organic matter.', ARRAY['May contain caffeine residues (allelopathic)', 'High acidity requires composting before application'], 'Coffee pulp is high in N (~2-3%) and K. Requires 2-3 months of composting to neutralize acidity and caffeine. Some coffee farms use organic certification (verify supplier claims).', 'Central American coffee cooperatives and processors', 'Coffee pulp is an abundant Central American agricultural byproduct during coffee harvest. Requires composting to neutralize acidity and caffeine allelopathy.', 'Coffee pulp: Central American agricultural byproduct, high in N and K. CAUTION: caffeine residues are allelopathic; high acidity requires 2-3 months of composting before application.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('south_america', 'Sugarcane bagasse', 'agricultural_byproduct', 'Brazil, Colombia, Argentina', 'South American sugarcane regions', 'Year-round (harvest season peaks)', 'Abundant byproduct of sugar and ethanol production. High in C and fiber. Excellent for compost bulking agent.', ARRAY['May contain pesticide residues', 'Very low N content; needs N-rich materials for balanced compost'], 'Sugarcane bagasse is high in C and fiber, low in N. Excellent compost bulking agent that improves aeration. Combine with N-rich manures for balanced compost.', 'South American sugar mills and ethanol producers', 'Sugarcane bagasse is an abundant South American agricultural byproduct. Excellent compost bulking agent due to high C content. Combine with N-rich manures for balanced compost.', 'Sugarcane bagasse: South American agricultural byproduct, high in C and fiber. Excellent compost bulking agent. CAUTION: very low N; combine with N-rich manures for balanced compost. May contain pesticide residues.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('latin_america_general', 'Sesbania green manure', 'green_manure', 'Latin America general', 'Tropical Latin America', 'Grown in situ, typically 60-90 day cycles', 'Fast-growing legume cover crop. N-fixing root nodules enrich soil. Tilled in before seed set.', ARRAY['Seeds may have low germination if not scarified', 'Can become invasive if not managed'], 'Sesbania is a fast-growing N-fixing legume. Green manure application adds ~3% N and significant organic matter. Best tilled in at flowering before seed set.', 'Latin American seed suppliers and agricultural cooperatives', 'Sesbania is a fast-growing N-fixing legume common in Latin America. Green manure application enriches soil with N and organic matter. Tilled in at flowering.', 'Sesbania green manure: Latin American N-fixing legume cover crop. Tilled in at flowering adds ~3% N and significant organic matter. CAUTION: seeds may need scarification; can become invasive if not managed.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('mexico', 'Ascophyllum nodosum (coastal)', 'marine_material', 'Mexico', 'Coastal Mexico (Baja California, Sonora, Veracruz)', 'Year-round (harvest regulated by season)', 'Brown kelp harvested from coastal Mexican waters. Used in foliar feeds and as soil amendment.', ARRAY['Regulated harvest to prevent over-exploitation', 'Quality varies with harvest season and processing'], 'Ascophyllum nodosum is high in K, natural cytokinins, and trace minerals. Mexican coastal kelp is a premium biofertilizer ingredient. Harvest is regulated to ensure sustainability.', 'Mexican kelp harvesters and processors (regulated)', 'Ascophyllum nodosum is a premium kelp biofertilizer ingredient harvested from coastal Mexican waters. High K, trace minerals, and natural growth hormones. Harvest is regulated for sustainability.', 'Ascophyllum nodosum: Mexican coastal kelp, high in K and natural growth hormones. CAUTION: regulated harvest to prevent over-exploitation; quality varies with season and processing. Premium biofertilizer ingredient for foliar application.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)'),
('caribbean', 'Coconut coir and husks', 'agricultural_byproduct', 'Dominican Republic, Philippines (LAC: Caribbean)', 'Caribbean and tropical LAC', 'Year-round', 'Byproduct of coconut processing. Coconut coir is excellent for vermicompost bedding. Husks can be chipped for mulch.', ARRAY['High lignin content slows decomposition', 'May contain salt if not properly processed'], 'Coconut coir is an excellent vermicompost bedding material with high water retention. Husks are high in lignin and slow to decompose. Both are abundant in the Caribbean.', 'Caribbean coconut processors and cooperatives', 'Coconut coir and husks are abundant Caribbean agricultural byproducts. Coir is excellent vermicompost bedding; husks provide slow-release mulch.', 'Coconut coir and husks: Caribbean agricultural byproducts. Coir is excellent vermicompost bedding; husks provide slow-release mulch. CAUTION: high lignin slows decomposition; may contain salt if not properly processed.', 'Bio-Organic Fertilizer Categories and Composition (Kokonut Biofactory research)')
ON CONFLICT DO NOTHING;
